/* list of tests. If your test is TEST(foo, bar) then you should
 * add TEST_FOUND(sd_test__foo_bar) here.
 */
TEST_FOUND(sd_test__dat_read_square_matrix)
TEST_FOUND(sd_test__err_basic)
TEST_FOUND(sd_test__exc_em)
TEST_FOUND(sd_test__exc_emcolor)
TEST_FOUND(sd_test__exc_heun)
TEST_FOUND(sd_test__hist_basic)
TEST_FOUND(sd_test__hist_exact)
TEST_FOUND(sd_test__log_custom_handler)
TEST_FOUND(sd_test__log_simple)
TEST_FOUND(sd_test__net_simple)
TEST_FOUND(sd_test__out_file)
TEST_FOUND(sd_test__out_mem)
TEST_FOUND(sd_test__out_sfilt)
TEST_FOUND(sd_test__out_tavg)
TEST_FOUND(sd_test__out_tee)
TEST_FOUND(sd_test__solv_simple)
TEST_FOUND(sd_test__test_sparse_test_sparse_from_dense)
TEST_FOUND(sd_test__util_uniqi)
TEST_FOUND(sd_test__malloc_reg0)
TEST_FOUND(sd_test__malloc_reg1)
TEST_FOUND(sd_test__malloc_reg2)
