/* list of tests. If your test is TEST(foo, bar) then you should
 * add TEST_FOUND(foo, bar) here.
 */
TEST_FOUND(arith, sum)
TEST_FOUND(dat_read_square, matrix)
TEST_FOUND(err, basic)
TEST_FOUND(exc, em)
TEST_FOUND(exc, emcolor)
TEST_FOUND(exc, heun)
TEST_FOUND(hist, basic)
TEST_FOUND(hist, exact)
TEST_FOUND(log_custom, handler)
TEST_FOUND(log, simple)
TEST_FOUND(net, simple)
TEST_FOUND(net, matmult)
TEST_FOUND(out, file)
TEST_FOUND(out, mem)
TEST_FOUND(out, sfilt)
TEST_FOUND(out, tavg)
TEST_FOUND(out, tee)
TEST_FOUND(out, conv)
TEST_FOUND(out, ign)
TEST_FOUND(solv, simple)
TEST_FOUND(sparse, fromdense)
TEST_FOUND(util, uniqi)
TEST_FOUND(malloc, reg0)
TEST_FOUND(malloc, reg1)
TEST_FOUND(malloc, reg2)
TEST_FOUND(hrf, glover)
TEST_FOUND(hrf, volt1)
TEST_FOUND(prng, simple)
