sddekit: src/out_sfilt.c File Reference
out_sfilt.c File Reference
#include "sddekit.h"
Data Structures
struct sfiltd
Typedefs
typedef struct sfiltd sfiltd
Functions
uint32_t get_nfilt (sd_out_sfilt *out)
uint32_t get_filtlen (sd_out_sfilt *out)
double * get_xfilts (sd_out_sfilt *out)
double * get_cfilts (sd_out_sfilt *out)
double * get_x (sd_out_sfilt *out)
double * get_c (sd_out_sfilt *out)
sd_out * get_out (sd_out_sfilt *out)
sd_out * get_next_out (sd_out_sfilt *out)
void sfilt_free (sd_out *out)
sd_out_sfilt * sd_out_sfilt_new (uint32_t nfilt, uint32_t filtlen, double *restrict xfilts, double *restrict cfilts, sd_out *next_out)
Typedef Documentation
typedef struct sfiltd sfiltd
Function Documentation
double* get_c (sd_out_sfilt * out)
Definition at line 23 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->c; }
double* get_cfilts (sd_out_sfilt * out)
Definition at line 21 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->cfilts; }
uint32_t get_filtlen (sd_out_sfilt * out)
Definition at line 19 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->filtlen; }
sd_out* get_next_out (sd_out_sfilt * out)
Definition at line 25 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->next_out; }
uint32_t get_nfilt (sd_out_sfilt * out)
Definition at line 18 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->nfilt; }
sd_out* get_out (sd_out_sfilt * out)
Definition at line 24 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->out; }
double* get_x (sd_out_sfilt * out)
Definition at line 22 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->x; }
double* get_xfilts (sd_out_sfilt * out)
Definition at line 20 of file out_sfilt.c.
References sd_out_sfilt::ptr.
 { return ((sfiltd*)out->ptr)->xfilts; }
sd_out_sfilt* sd_out_sfilt_new (uint32_t nfilt, uint32_t filtlen, double *restrict xfilts, double *restrict cfilts, sd_out * out)
Create instance of spatial filter output.
Parameters
nfilt number of spatial filters
filtlen length of filter coefficients.
xfilts filter coefficients for state variablex.
cfilts filter coefficients for coupling variables.
out output callback to pass filtered data to.
Definition at line 74 of file out_sfilt.c.
References sfiltd::c, sfiltd::cfilts, sfiltd::filtlen, sfiltd::next_out, sfiltd::nfilt, sfiltd::out, sd_out::ptr, sd_out_sfilt::ptr, sd_err, sd_free(), sd_malloc(), sfiltd::sfilt, sfiltd::x, and sfiltd::xfilts.
 {
     uint32_t n_filt_bytes;
     sfiltd *d, zd = { 0 };
     n_filt_bytes = nfilt * filtlen * sizeof(double);
     if ((d = sd_malloc(sizeof(sfiltd))) == NULL
         || (*d = zd, nfilt < 1 || filtlen < 1)
         || (d->out = sd_malloc(sizeof(sd_out))) == NULL
         || (d->sfilt = sd_malloc(sizeof(sd_out_sfilt))) == NULL
         || (d->xfilts = sd_malloc(n_filt_bytes)) == NULL
         || (d->cfilts = sd_malloc(n_filt_bytes)) == NULL
         || (d->x = sd_malloc(sizeof(double) * nfilt)) == NULL
         || (d->c = sd_malloc(sizeof(double) * nfilt)) == NULL
         )
     {
         if (d->xfilts!=NULL) sd_free(d->xfilts);
         if (d->cfilts!=NULL) sd_free(d->cfilts);
         if (d->x!=NULL) sd_free(d->x);
         if (d->sfilt != NULL) sd_free(d->sfilt);
         if (d->out != NULL) sd_free(d->out);
         sd_free(d);
         sd_err("nfilt < 1, filtlen < 1 or memory alloc failed.");
         return NULL;
     }
     d->nfilt = nfilt;
     d->filtlen = filtlen;
     memcpy(d->xfilts, xfilts, n_filt_bytes);
     memcpy(d->cfilts, cfilts, n_filt_bytes);
     d->next_out = next_out;
     *(d->out) = sfilt_out_defaults;
     *(d->sfilt) = sfilt_defaults;
     d->out->ptr = d->sfilt->ptr = d;
     return d->sfilt;
 }
void sfilt_free (sd_out * out)
Definition at line 44 of file out_sfilt.c.
References sfiltd::c, sfiltd::cfilts, sfiltd::out, sd_out::ptr, sd_free(), sfiltd::sfilt, sfiltd::x, and sfiltd::xfilts.
{
     sfiltd *d = out->ptr;
     sd_free(d->xfilts);
     sd_free(d->cfilts);
     sd_free(d->x);
     sd_free(d->c);
     sd_free(d->out);
     sd_free(d->sfilt);
     sd_free(d);
 }