sddekit: src/randomkit.c File Reference
randomkit.c File Reference
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <limits.h>
#include <math.h>
#include <time.h>
#include <sys/time.h>
#include <unistd.h>
#include "randomkit.h"
Macros
#define RK_NO_WINCRYPT
#define RK_DEV_URANDOM "/dev/urandom"
#define RK_DEV_RANDOM "/dev/random"
#define N 624
#define M 397
#define MATRIX_A 0x9908b0dfUL
#define UPPER_MASK 0x80000000UL
#define LOWER_MASK 0x7fffffffUL
Functions
void rk_seed (unsigned long seed, rk_state *state)
rk_error rk_randomseed (rk_state *state)
unsigned long rk_random (rk_state *state)
long rk_long (rk_state *state)
unsigned long rk_ulong (rk_state *state)
unsigned long rk_interval (unsigned long max, rk_state *state)
double rk_double (rk_state *state)
void rk_fill (void *buffer, size_t size, rk_state *state)
rk_error rk_devfill (void *buffer, size_t size, int strong)
rk_error rk_altfill (void *buffer, size_t size, int strong, rk_state *state)
double rk_gauss (rk_state *state)
void rk_gauss_fill (rk_state *state, int nx, double *x)
Variables
char * rk_strerror [RK_ERR_MAX]
Macro Definition Documentation
#define LOWER_MASK 0x7fffffffUL
Definition at line 211 of file randomkit.c.
Referenced by rk_random().
#define M 397
Definition at line 208 of file randomkit.c.
Referenced by rk_random(), sd_net_new_het(), and sd_net_new_hom().
#define MATRIX_A 0x9908b0dfUL
Definition at line 209 of file randomkit.c.
Referenced by rk_random().
#define N 624
Definition at line 207 of file randomkit.c.
Referenced by rk_random().
#define RK_DEV_RANDOM "/dev/random"
Definition at line 128 of file randomkit.c.
Referenced by rk_devfill().
#define RK_DEV_URANDOM "/dev/urandom"
Definition at line 124 of file randomkit.c.
Referenced by rk_devfill().
#define RK_NO_WINCRYPT
Definition at line 75 of file randomkit.c.
#define UPPER_MASK 0x80000000UL
Definition at line 210 of file randomkit.c.
Referenced by rk_random().
Function Documentation
rk_error rk_altfill (void * buffer, size_t size, int strong, rk_state * state)
Definition at line 368 of file randomkit.c.
References rk_devfill(), and rk_fill().
 {
     rk_error err;
     err = rk_devfill(buffer, size, strong);
     if (err) {
         rk_fill(buffer, size, state);
     }
     return err;
 }
rk_error rk_devfill (void * buffer, size_t size, int strong)
Definition at line 326 of file randomkit.c.
References RK_DEV_RANDOM, RK_DEV_URANDOM, RK_ENODEV, and RK_NOERR.
Referenced by rk_altfill(), and rk_randomseed().
 {
 #ifndef _WIN32
     FILE *rfile;
     int done;
     if (strong) {
         rfile = fopen(RK_DEV_RANDOM, "rb");
     }
     else {
         rfile = fopen(RK_DEV_URANDOM, "rb");
     }
     if (rfile == NULL) {
         return RK_ENODEV;
     }
     done = fread(buffer, size, 1, rfile);
     fclose(rfile);
     if (done) {
         return RK_NOERR;
     }
 #else
 #ifndef RK_NO_WINCRYPT
     HCRYPTPROV hCryptProv;
     BOOL done;
     if (!CryptAcquireContext(&hCryptProv, NULL, NULL, PROV_RSA_FULL,
             CRYPT_VERIFYCONTEXT) || !hCryptProv) {
         return RK_ENODEV;
     }
     done = CryptGenRandom(hCryptProv, size, (unsigned char *)buffer);
     CryptReleaseContext(hCryptProv, 0);
     if (done) {
         return RK_NOERR;
     }
 #endif
 #endif
     return RK_ENODEV;
 }
double rk_double (rk_state * state)
Returns a random double between 0.0 and 1.0, 1.0 excluded.
Definition at line 295 of file randomkit.c.
References rk_random().
Referenced by rk_gauss(), and rk_gauss_fill().
 {
     /* shifts : 67108864 = 0x4000000, 9007199254740992 = 0x20000000000000 */
     long a = rk_random(state) >> 5, b = rk_random(state) >> 6;
     return (a * 67108864.0 + b) / 9007199254740992.0;
 }
void rk_fill (void * buffer, size_t size, rk_state * state)
Definition at line 303 of file randomkit.c.
References rk_random().
Referenced by rk_altfill().
 {
     unsigned long r;
     unsigned char *buf = buffer;
     for (; size >= 4; size -= 4) {
         r = rk_random(state);
         *(buf++) = r & 0xFF;
         *(buf++) = (r >> 8) & 0xFF;
         *(buf++) = (r >> 16) & 0xFF;
         *(buf++) = (r >> 24) & 0xFF;
     }
     if (!size) {
         return;
     }
     r = rk_random(state);
     for (; size; r >>= 8, size --) {
         *(buf++) = (unsigned char)(r & 0xFF);
     }
 }
double rk_gauss (rk_state * state)
return a random gaussian deviate with variance unity and zero mean.
Definition at line 380 of file randomkit.c.
References rk_state_::gauss, rk_state_::has_gauss, and rk_double().
 {
     if (state->has_gauss) {
         const double tmp = state->gauss;
         state->gauss = 0;
         state->has_gauss = 0;
         return tmp;
     }
     else {
         double f, x1, x2, r2;
         do {
             x1 = 2.0*rk_double(state) - 1.0;
             x2 = 2.0*rk_double(state) - 1.0;
             r2 = x1*x1 + x2*x2;
         }
         while (r2 >= 1.0 || r2 == 0.0);
         /* Box-Muller transform */
         f = sqrt(-2.0*log(r2)/r2);
         /* Keep for next call */
         state->gauss = f*x1;
         state->has_gauss = 1;
         return f*x2;
     }
 }
void rk_gauss_fill (rk_state * state, int nx, double * x)
fill a double buffer with gaussian numbers
Definition at line 408 of file randomkit.c.
References rk_state_::gauss, rk_state_::has_gauss, and rk_double().
 {
     int i;
     for (i=0; i<nx; i++)
     {
         if (state->has_gauss) {
             const double tmp = state->gauss;
             state->gauss = 0;
             state->has_gauss = 0;
             x[i] = tmp;
         }
         else {
             double f, x1, x2, r2;
             do {
                 x1 = 2.0*rk_double(state) - 1.0;
                 x2 = 2.0*rk_double(state) - 1.0;
                 r2 = x1*x1 + x2*x2;
             }
             while (r2 >= 1.0 || r2 == 0.0);
             /* Box-Muller transform */
             f = sqrt(-2.0*log(r2)/r2);
             /* Keep for next call */
             state->gauss = f*x1;
             state->has_gauss = 1;
             x[i] = f*x2;
         }
     }
 }
unsigned long rk_interval (unsigned long max, rk_state * state)
Definition at line 263 of file randomkit.c.
References rk_random(), and rk_ulong().
 {
     unsigned long mask = max, value;
     if (max == 0) {
         return 0;
     }
     /* Smallest bit mask >= max */
     mask |= mask >> 1;
     mask |= mask >> 2;
     mask |= mask >> 4;
     mask |= mask >> 8;
     mask |= mask >> 16;
 #if ULONG_MAX > 0xffffffffUL
     mask |= mask >> 32;
 #endif
     /* Search a random value in [0..mask] <= max */
 #if ULONG_MAX > 0xffffffffUL
     if (max <= 0xffffffffUL) {
         while ((value = (rk_random(state) & mask)) > max);
     }
     else {
         while ((value = (rk_ulong(state) & mask)) > max);
     }
 #else
     while ((value = (rk_ulong(state) & mask)) > max);
 #endif
     return value;
 }
long rk_long (rk_state * state)
Definition at line 247 of file randomkit.c.
References rk_ulong().
 {
     return rk_ulong(state) >> 1;
 }
unsigned long rk_random (rk_state * state)
Definition at line 215 of file randomkit.c.
References rk_state_::key, LOWER_MASK, M, MATRIX_A, N, rk_state_::pos, RK_STATE_LEN, and UPPER_MASK.
Referenced by rk_double(), rk_fill(), rk_interval(), and rk_ulong().
 {
     unsigned long y;
     if (state->pos == RK_STATE_LEN) {
         int i;
         for (i = 0; i < N - M; i++) {
             y = (state->key[i] & UPPER_MASK) | (state->key[i+1] & LOWER_MASK);
             state->key[i] = state->key[i+M] ^ (y>>1) ^ (-(y & 1) & MATRIX_A);
         }
         for (; i < N - 1; i++) {
             y = (state->key[i] & UPPER_MASK) | (state->key[i+1] & LOWER_MASK);
             state->key[i] = state->key[i+(M-N)] ^ (y>>1) ^ (-(y & 1) & MATRIX_A);
         }
         y = (state->key[N - 1] & UPPER_MASK) | (state->key[0] & LOWER_MASK);
         state->key[N - 1] = state->key[M - 1] ^ (y >> 1) ^ (-(y & 1) & MATRIX_A);
         state->pos = 0;
     }
     y = state->key[state->pos++];
     /* Tempering */
     y ^= (y >> 11);
     y ^= (y << 7) & 0x9d2c5680UL;
     y ^= (y << 15) & 0xefc60000UL;
     y ^= (y >> 18);
     return y;
 }
rk_error rk_randomseed (rk_state * state)
Definition at line 171 of file randomkit.c.
References rk_state_::gauss, rk_state_::has_binomial, rk_state_::has_gauss, rk_state_::key, rk_state_::pos, rk_devfill(), RK_ENODEV, RK_NOERR, rk_seed(), and RK_STATE_LEN.
 {
 #ifndef _WIN32
     struct timeval tv;
 #else
     struct _timeb  tv;
 #endif
     int i;
     if (rk_devfill(state->key, sizeof(state->key), 0) == RK_NOERR) {
         /* ensures non-zero key */
         state->key[0] |= 0x80000000UL;
         state->pos = RK_STATE_LEN;
         state->gauss = 0;
         state->has_gauss = 0;
         state->has_binomial = 0;
         for (i = 0; i < 624; i++) {
             state->key[i] &= 0xffffffffUL;
         }
         return RK_NOERR;
     }
 #ifndef _WIN32
     gettimeofday(&tv, NULL);
     rk_seed(rk_hash(getpid()) ^ rk_hash(tv.tv_sec) ^ rk_hash(tv.tv_usec)
             ^ rk_hash(clock()), state);
 #else
     _FTIME(&tv);
     rk_seed(rk_hash(tv.time) ^ rk_hash(tv.millitm) ^ rk_hash(clock()), state);
 #endif
     return RK_ENODEV;
 }
void rk_seed (unsigned long seed, rk_state * state)
Initialize the RNG state using the given seed.
Definition at line 141 of file randomkit.c.
References rk_state_::gauss, rk_state_::has_binomial, rk_state_::has_gauss, rk_state_::key, rk_state_::pos, and RK_STATE_LEN.
Referenced by rk_randomseed().
 {
     int pos;
     seed &= 0xffffffffUL;
     /* Knuth's PRNG as used in the Mersenne Twister reference implementation */
     for (pos = 0; pos < RK_STATE_LEN; pos++) {
         state->key[pos] = seed;
         seed = (1812433253UL * (seed ^ (seed >> 30)) + pos + 1) & 0xffffffffUL;
     }
     state->pos = RK_STATE_LEN;
     state->gauss = 0;
     state->has_gauss = 0;
     state->has_binomial = 0;
 }
unsigned long rk_ulong (rk_state * state)
Definition at line 253 of file randomkit.c.
References rk_random().
Referenced by rk_interval(), and rk_long().
 {
 #if ULONG_MAX <= 0xffffffffUL
     return rk_random(state);
 #else
     return (rk_random(state) << 32) | (rk_random(state));
 #endif
 }
Variable Documentation
char* rk_strerror[RK_ERR_MAX]
Initial value:
=
{
    "no error",
    "random device unvavailable"
}
Definition at line 131 of file randomkit.c.