sddekit: src/sd_hist.c File Reference
sd_hist.c File Reference
#include "sddekit.h"
Data Structures
struct hist_data
Typedefs
typedef struct hist_data hist_data
Functions
uint32_t get_maxvi (sd_hist *h)
uint32_t get_vi2i (sd_hist *h, uint32_t vi)
sd_hist * sd_hist_new_default (uint32_t nd, uint32_t *vi, double *vd, double t0, double dt)
sd_hfill * sd_hfill_new_val (double val)
Typedef Documentation
typedef struct hist_data hist_data
Function Documentation
uint32_t get_maxvi (sd_hist * h)
Definition at line 13 of file sd_hist.c.
References sd_hist::ptr.
 { return ((hist_data*) h->ptr)->maxvi; }
uint32_t get_vi2i (sd_hist * h, uint32_t vi)
Definition at line 14 of file sd_hist.c.
References sd_hist::ptr.
 { return ((hist_data*) h->ptr)->vi2i[vi]; }
sd_hfill* sd_hfill_new_val (double val)
An sd_hfill instance which sets all elements of the history buffer to a given value.
Definition at line 406 of file sd_hist.c.
References sd_hfill::apply, sd_hfill::free, sd_hfill::ptr, sd_err, and sd_malloc().
 {
     sd_hfill *hf;
     if ((hf=sd_malloc(sizeof(sd_hfill))) == NULL
         || (hf->ptr=sd_malloc(sizeof(double))) == NULL)
     {
         sd_err("alloc hfill failed.");
         return hf;
     }
     *((double*)hf->ptr) = val;
     hf->free = &val_fill_free;
     hf->apply = &val_fill_apply;
     return hf;
 }
sd_hist* sd_hist_new_default (uint32_t nd, uint32_t * vi, double * vd, double t0, double dt)
Initialize an history instance.
Parameters
h an allocated history instance.
nd number of delayed coupling terms.
vi efferent index of each delayed coupling term.
vd delay of each delayed coupling term.
t0 starting time.
dt time-step to use in history buffer (need not equal solution dt).
Returns
initialized history instance or NULL if error occurs.
Definition at line 353 of file sd_hist.c.
References hist_data::buf, hist_data::del, hist_data::dt, hist_data::lim, hist_data::nd, hist_data::nu, sd_hist::ptr, sd_err, sd_free(), sd_malloc(), SD_OK, sd_util_uniqi(), hist_data::t, hist_data::uvi, and hist_data::vi.
Referenced by sd_sol_new_default().
 {
     sd_hist *hist;
     hist_data *h = NULL, zh = { 0 };
     if ((hist = sd_malloc(sizeof(sd_hist))) == NULL
         || (h = hist->ptr = sd_malloc(sizeof(hist_data))) == NULL
         || (*h = zh, (h->nd = nd) < 1)
         || sd_util_uniqi(nd, vi, &(h->nu), &(h->uvi)) != SD_OK
         || (h->del = sd_malloc(sizeof(double) * nd)) == NULL
         || (h->vi = sd_malloc(sizeof(uint32_t) * nd)) == NULL
         || (memcpy(h->del, vd, nd * sizeof(double)),
             memcpy(h->vi, vi, nd * sizeof(uint32_t)),
             0)
         || setup_buffer_structure(h, dt) != SD_OK
         || (h->buf = sd_malloc(sizeof(double) * h->lim[h->nu])) == NULL
         )
     {
         if (hist != NULL) sd_free(hist);
         if (h != NULL)
         {
             if (h->buf!=NULL) sd_free(h->buf);
             if (h->uvi!=NULL) sd_free(h->uvi);
             if (h->del!=NULL) sd_free(h->del);
             if (h->vi!=NULL) sd_free(h->vi);
         }
         sd_err("number of delays < 1 or memory alloc failed.");
         return NULL;
     }
     h->dt = dt;
     h->t = t0;
     *hist = sd_hist_defaults;
     hist->ptr = h;
     return hist;
 }