sddekit: src/sd_solv.c File Reference
sd_solv.c File Reference
#include "sddekit.h"
Data Structures
struct sol_data
Macros
#define FAILIF(cond, msg)
Typedefs
typedef struct sol_data sol_data
Functions
sd_sol * sd_sol_new_default (sd_sys *sys, sd_sch *scheme, sd_out *out, sd_hfill *hf, uint32_t seed, uint32_t nx, double *restrict x0, uint32_t nce, uint32_t nca, uint32_t *restrict vi, double *restrict vd, double t0, double dt)
Macro Definition Documentation
#define FAILIF (cond, msg)
Value:
if (cond) { \
        errmsg = msg;\
        goto uhoh;\
    }
Referenced by sd_sol_new_default().
Typedef Documentation
typedef struct sol_data sol_data
Function Documentation
sd_sol* sd_sol_new_default (sd_sys * sys, sd_sch * scheme, sd_out * out, sd_hfill * hf, uint32_t seed, uint32_t nx, double *restrict x0, uint32_t nce, uint32_t nca, uint32_t *restrict vi, double *restrict vd, double t0, double dt)
Create a new default solver instance.
Parameters
sys system to be integrated.
scheme time-stepping scheme to use for solution.
out output handler.
hf history filler.
seed seed for random number generation.
nx number of state variables.
x0 initial state at t = 0.
nce number of coupling variables emit by system.
nca number of coupling variables accpted by system.
vi indices of coupling variables (length nca).
vd delays of coupling variables (length nca, strictly positive).
t0 starting time.
dt time step.
Definition at line 77 of file sd_solv.c.
References sol_data::c, sol_data::cont, sol_data::dt, FAILIF, sd_hist::fill, sd_hist::free, sol_data::hf, sol_data::hist, sol_data::nca, sol_data::nce, sol_data::nx, sol_data::out, sd_sol::ptr, sol_data::rng, sol_data::sch, sd_err, sd_free(), sd_hist_new_default(), sd_malloc(), SD_OK, sd_rng_new_default(), sd_rng::seed, sol_data::sys, sol_data::t, sol_data::x, and sol_data::x0.
 {
     char *errmsg;
     sd_sol *sol = NULL;
     /* error handling */
 #define FAILIF(cond, msg)\
         if (cond) { \
         errmsg = msg;\
         goto uhoh;\
     }
     /* allocate & zero sol interface & data */
     {
         sol_data zdat = { 0 };
         FAILIF((sol = sd_malloc(sizeof(sd_sol)))==NULL, "allocating solver failed.");
         *sol = sol_default;
         FAILIF((sol->ptr = sd_malloc(sizeof(sol_data)))==NULL, "allocating solver data failed.");
         *((sol_data*) sol->ptr) = zdat;
         /* TODO fill interface table */
     }
     FAILIF(sys == NULL || scheme == NULL || hf == NULL || out == NULL,
         "cannot initialize solver with NULL system, scheme, out or history function.")
     /* copy arguments */
     {
         sol_data *s = (sol_data*)sol->ptr;
         s->nx = nx;
         s->nce = nce;
         s->nca = nca;
         s->cont = 1;
         s->sys = sys;
         s->sch = scheme;
         s->out = out;
         s->hf = hf;
     }
     /* setup coupling */
     {
         sol_data *s = (sol_data*)sol->ptr;
         if (nca > 0 && vi!=NULL && vd!=NULL)
             {
                 size_t cn;
                 FAILIF((s->hist = sd_hist_new_default(nca, vi, vd, t0, dt)) == NULL, "failed to create history.")
                 FAILIF(s->hist->fill(s->hist, hf)!=SD_OK, "history fill failed.")
                 /* s->c big enough to accomate aff or eff */
                 cn = nca > nce ? nca : nce;
                 FAILIF((s->c = sd_malloc(sizeof(double) * cn)) == NULL, "alloc coupling array failed.")
         } else {
             s->nca = 0;
             s->c = NULL;
         }
     }
     /* initial conditions */
     {
         sol_data *s = (sol_data*)sol->ptr;
         FAILIF((s->rng = sd_rng_new_default())==NULL,
             "couldn't create a new rng");
         s->rng->seed(s->rng, seed);
         FAILIF((s->x = sd_malloc (sizeof(double) * nx))==NULL,
                 "failed to alloc solver x")
         FAILIF((s->x0 = sd_malloc (sizeof(double) * nx))==NULL,
             "failed to alloc solver x0")
         memcpy(s->x, x0, sizeof(double) * s->nx);
         memcpy(s->x0, x0, sizeof(double) * s->nx);
         s->t = t0;
         s->dt = dt;
     }
     return sol;
 uhoh:
     /* clean up */
     {
         if (sol != NULL && sol->ptr != NULL)
         {
             sol_data *s = sol->ptr;
             if (s->x!=NULL) sd_free(s->x);
             if (s->x0!=NULL) sd_free(s->x0);
             if (s->c!=NULL) sd_free(s->c);
             if (s->hist!=NULL) s->hist->free(s->hist);
         }
         if (sol != NULL)
             sd_free(sol);
     }
     sd_err(errmsg);
     return NULL;
 }