sddekit: src/sd_malloc.c File Reference
sd_malloc.c File Reference
#include "sddekit.h"
Functions
void sd_malloc_set_allocators (sd_malloc_t malloc, sd_realloc_t realloc, sd_free_t free)
void sd_malloc_set_stdlib_allocators ()
void * sd_malloc (size_t size)
void * sd_realloc (void *ptr, size_t size)
void sd_free (void *ptr)
Function Documentation
void sd_free (void * ptr)
Free memory using current allocator.
Definition at line 43 of file sd_malloc.c.
References sd_log_debug.
Referenced by one_step_free(), sd_hist_new_default(), sd_net_new_hom(), sd_out_sfilt_new(), sd_out_tee_new(), sd_rng_new_default(), sd_sch_new_emc(), sd_sch_new_heun(), sd_sol_new_default(), sd_sparse_from_dense(), sd_util_uniqi(), and sfilt_free().
{
 #ifdef SDDEBUGFREE
     static int n = 0;
 #endif
     if (ptr==NULL) {
         sd_log_debug( "[sd_free] cowardly refusing to free a NULL pointer." );
         return;
     }
 #ifdef SDDEBUGFREE
     sd_log_debug("%d'th call to sd_free on %p.", n, ptr);
     n++;
 #endif
     (*_sd_free)(ptr);
 }
void* sd_malloc (size_t size)
Allocate memory using current allocator.
Definition at line 27 of file sd_malloc.c.
References sd_err.
Referenced by sd_hfill_new_val(), sd_hist_new_default(), sd_net_new_het(), sd_net_new_hom(), sd_out_mem_new(), sd_out_new_cb(), sd_out_new_until(), sd_out_sfilt_new(), sd_out_tavg_new(), sd_out_tee_new(), sd_rng_new_default(), sd_sch_new_cb(), sd_sch_new_emc(), sd_sch_new_heun(), sd_sol_new_default(), sd_sparse_from_dense(), sd_sys_exc_new(), sd_sys_new_cb(), sd_util_read_square_matrix(), and sd_util_uniqi().
{
     void *new_ptr;
     new_ptr = (*_sd_malloc)(size);
     if (new_ptr==NULL)
         sd_err( "[sd_alloc] alloc returned a NULL pointer." );
     return new_ptr;
 }
void sd_malloc_set_allocators (sd_malloc_t malloc, sd_realloc_t realloc, sd_free_t free)
Set custom allocators to be used whenever sd_ calls require allocating or freeing memory.
Definition at line 13 of file sd_malloc.c.
References sd_err.
Referenced by sd_malloc_set_stdlib_allocators().
{
     if (malloc == NULL || realloc == NULL || free == NULL) {
         sd_err( "sd_malloc_set_allocators passed a NULL allocator." );
         return;
     }
     _sd_malloc = malloc;
     _sd_realloc = realloc;
     _sd_free = free;
 }
void sd_malloc_set_stdlib_allocators ()
Set allocators to stdlib functions (malloc, realloc, free)
Definition at line 23 of file sd_malloc.c.
References sd_malloc_set_allocators().
{
     sd_malloc_set_allocators(&malloc, &realloc, &free);
 }
void* sd_realloc (void * ptr, size_t size)
Allocate memory using current allocator.
Definition at line 35 of file sd_malloc.c.
References sd_err.
{
     void *new_ptr;
     new_ptr = (*_sd_realloc)(ptr, size);
     if (new_ptr==NULL)
         sd_err( "[sd_realloc] realloc returned a NULL pointer." );
     return new_ptr;
 }