sddekit: src/sd_scheme.c File Reference
sd_scheme.c File Reference
#include "sddekit.h"
Data Structures
struct one_step_data
struct emc_data
struct heun_data
Typedefs
typedef struct one_step_data one_step_data
typedef struct emc_data emc_data
typedef struct heun_data heun_data
Functions
void one_step_free (sd_sch *sch)
sd_sch * sd_sch_new_id (uint32_t nx)
sd_sch * sd_sch_new_em (uint32_t nx)
double sd_sch_emc_get_lam (sd_sch *sch)
sd_sch * sd_sch_new_emc (uint32_t nx, double lam)
sd_sch * sd_sch_new_heun (uint32_t nx)
Typedef Documentation
typedef struct emc_data emc_data
typedef struct heun_data heun_data
typedef struct one_step_data one_step_data
Function Documentation
void one_step_free (sd_sch * sch)
Definition at line 13 of file sd_scheme.c.
References one_step_data::f, one_step_data::g, sd_sch::ptr, sd_free(), and one_step_data::z.
 {
     one_step_data *d = sch->ptr;
     sd_free(d->f);
     sd_free(d->g);
     sd_free(d->z);
     sd_free(d);
 }
double sd_sch_emc_get_lam (sd_sch * sch)
Definition at line 136 of file sd_scheme.c.
 {
     return ((emc_data*)sch)->lam;
 }
sd_sch* sd_sch_new_em (uint32_t nx)
Definition at line 116 of file sd_scheme.c.
 {
     sd_sch *new = new_one_step(nx);
     new->apply = &em_apply;
     return new;
 }
sd_sch* sd_sch_new_emc (uint32_t nx, double lam)
Definition at line 191 of file sd_scheme.c.
References sd_sch::apply, emc_data::eps, emc_data::f, emc_data::first_call, sd_sch::free, emc_data::g, sd_sch::get_nx, emc_data::lam, emc_data::nx, sd_sch::ptr, sd_err, sd_free(), sd_malloc(), and emc_data::z.
 {
     bool err;
     emc_data *d;
     sd_sch *sch;
     if ((d = sd_malloc(sizeof(emc_data))) == NULL) {
         sd_err("memory alloc for one step sch failed.");
         return NULL;
     }
     {
         emc_data zero = { 0 };
         *d = zero;
     }
     d->nx = nx;
     err = (sch = sd_malloc(sizeof(sd_sch))) == NULL;
     err |= (d->f=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->g=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->z=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->eps=sd_malloc(sizeof(double)*nx))==NULL;
     if (err) {
         if (d->f!=NULL) sd_free(d->f);
         if (d->g!=NULL) sd_free(d->g);
         if (d->z!=NULL) sd_free(d->z);
         if (d->eps!=NULL) sd_free(d->eps);
         if (d != NULL) sd_free(d);
         if (sch != NULL) sd_free(sch);
         sd_err("memory alloc for sch em color failed.");
         return NULL;
     }
     d->first_call = true;
     d->lam = lam;
     sch->ptr = d;
     sch->get_nx = &emc_get_nx;
     sch->apply = &emc_apply;
     sch->free = &emc_free;
     return sch;
 }
sd_sch* sd_sch_new_heun (uint32_t nx)
Definition at line 291 of file sd_scheme.c.
References sd_sch::apply, heun_data::fl, heun_data::fr, sd_sch::free, sd_sch::get_nx, heun_data::gl, heun_data::gr, heun_data::nx, sd_sch::ptr, sd_err, sd_free(), sd_malloc(), heun_data::xr, and heun_data::z.
 {
     bool err;
     heun_data *d;
     sd_sch *sch;
     if ((d = sd_malloc(sizeof(heun_data))) == NULL)
     {
         sd_err("memory alloc for heun scheme failed.");
         return NULL;
     }
     {
         heun_data zero = { 0 };
         *d = zero;
     }
     d->nx = nx;
     err = (sch = sd_malloc(sizeof(sd_sch)))==NULL;
     err |= (d->fl=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->fr=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->gl=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->gr=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->z=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->xr=sd_malloc(sizeof(double)*nx))==NULL;
     if (err) {
         if (d->fl!=NULL) sd_free(d->fl);;
         if (d->fr!=NULL) sd_free(d->fr);;
         if (d->gl!=NULL) sd_free(d->gl);;
         if (d->gr!=NULL) sd_free(d->gr);;
         if (d->z!=NULL) sd_free(d->z);;
         if (d->xr!=NULL) sd_free(d->xr);;
         if (d != NULL) sd_free(d);
         if (sch != NULL) sd_free(sch);
         sd_err("memory alloc durong sch em init failed.");
         return NULL;
     }
     sch->ptr = d;
     sch->get_nx = &heun_get_nx;
     sch->apply = &heun_apply;
     sch->free = &heun_free;
     return sch;
 }
sd_sch* sd_sch_new_id (uint32_t nx)
Create instance of the identity scheme
The identity schemes updates the state following f & g directly, i.e.
x_{t+1} = f(x_t) + g(x_t) * z
This is useful for difference equations, for example.
Parameters
d allocated scheme instance.
nx number of state variables.
Definition at line 109 of file sd_scheme.c.
 {
     sd_sch *new = new_one_step(nx);
     new->apply = &id_apply;
     return new;
 }