sddekit: src/sd_util.c File Reference
sd_util.c File Reference
#include "sddekit.h"
Functions
sd_stat sd_util_uniqi (uint32_t n, uint32_t *restrict ints, uint32_t *restrict nuniq, uint32_t **uints)
sd_stat sd_util_read_square_matrix (const char *fname, uint32_t *n, double **w)
Function Documentation
sd_stat sd_util_read_square_matrix (const char * fname, uint32_t * n, double ** w)
Read a square matrix from file in ascii format into w.
Note
w must be freed by user.
Parameters
[in] fname string containing filename to readable file.
[out] n number of rows & cols.
[out] w matrix of weights.
Returns
SD_OK if succeeds, SD_ERR if error occurs..
Definition at line 65 of file sd_util.c.
References SD_ERR, sd_err, sd_malloc(), and SD_OK.
 {
     uint32_t nn;
     FILE *fd;
     double _, *wi;
     /* open file */
     fd = fopen(fname, "r");
     if (fd==NULL) {
         sd_err("failed to open file");
         return SD_ERR;
     }
     /* count number of readable elements */
     nn = 0;
     {
         int count;
         while (1) {
             count = fscanf(fd, "%lg", &_);
             if (count < 1)
                 break;
             nn++;
         }
     }
     rewind(fd);
     /* setup memory */
     *n = (uint32_t) sqrt(nn);
     wi = sd_malloc (sizeof(double)*nn);
     *w = wi;
     if (wi==NULL) {
         fclose(fd);
         return SD_ERR;
     }
     /* read data into memory this time */
     {
         int count;
         while (1) {
             count = fscanf(fd, "%lg", wi++);
             if (count < 1)
                 break;
         }
     }
     fclose(fd);
     return SD_OK;
 }
sd_stat sd_util_uniqi (uint32_t n, uint32_t *restrict ints, uint32_t *restrict nuniq, uint32_t ** uints)
Obtain unique sorted integers.
Note
Caller must free uints when done.
Parameters
n number of elements
ints array of at least n integers.
[out] nuniq address of number of unique integers.
[out] uints address of array of unique integers.
Returns
Returns SD_OK if call succeeds, SD_ERR if error occurs.
Definition at line 12 of file sd_util.c.
References SD_ERR, sd_err, sd_free(), sd_malloc(), and SD_OK.
Referenced by sd_hist_new_default().
 {
     uint32_t i, j, *ints_copy;
     if (n==0) return SD_OK;
     if (n==1) {
         *nuniq = 1;
         if ((*uints = sd_malloc (sizeof(uint32_t)))==NULL) {
             sd_err("failed to allocate memory for unique integers");
             return SD_ERR;
         }
         (*uints)[0] = ints[0];
         return SD_OK;
     }
     /* sort copy of input vector */
     if ((ints_copy = sd_malloc(sizeof(uint32_t) * n))==NULL) {
         sd_err("failed to allocate memory for ints copy.");
         return SD_ERR;
     }
     memcpy(ints_copy, ints, n*sizeof(uint32_t));
     qsort(ints_copy, n, sizeof(uint32_t), compare_int);
     /* count uniq */
     *nuniq = 1;
     for (i=0; i<(n-1); i++)
         if (ints_copy[i] != ints_copy[i+1])
             (*nuniq)++;
     if ((*uints = sd_malloc (sizeof(uint32_t) * *nuniq))==NULL) {
         sd_err("failed to allocate memory for unique integers.");
         sd_free(ints_copy);
         return SD_ERR;
     }
     /* copy unique into output array */
     j = 0;
     (*uints)[j++] = ints_copy[0];
     for (i=0; i<(n-1); i++)
         if (ints_copy[i] != ints_copy[i+1])
             (*uints)[j++] = ints_copy[i+1];
     sd_free(ints_copy);
     return SD_OK;
 }