sddekit: src/sd_rng.c File Reference
sd_rng.c File Reference
#include "sddekit.h"
#include "randomkit.h"
Data Structures
struct rng_data
Functions
sd_rng * sd_rng_new_default ()
Function Documentation
sd_rng* sd_rng_new_default ()
Construct a new RNG from default implementation.
Definition at line 56 of file sd_rng.c.
References sd_rng::ptr, sd_err, sd_free(), and sd_malloc().
Referenced by sd_sol_new_default().
 {
     sd_rng *r, z = { 0 };
     if ((r = sd_malloc (sizeof(sd_rng))) == NULL
      || (*r = rng_default, 0)
      || (r->ptr = sd_malloc (sizeof(struct rng_data))) == NULL)
     {
         sd_free(r);
         sd_err("alloc rng failed.");
         return NULL;
     }
     return r;
 }