sddekit: src/sddekit.h File Reference
sddekit.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
Data Structures
struct sd_rng
struct sd_hfill
struct sd_hist
struct sd_sys_in
struct sd_sys_out
struct sd_sys
struct sd_sys_exc
struct sd_net
struct sd_out
struct sd_out_file
struct sd_out_mem
struct sd_out_tee
struct sd_out_tavg
struct sd_out_sfilt
struct sd_sch
struct sd_sol
Macros
#define SD_API
#define restrict
#define SD_AS(obj, type) (((obj)->type)(obj))
#define SD_CALL_AS(obj, type, meth, ...) SD_AS(obj, type)->meth(SD_AS(obj, type), __VA_ARGS__)
#define SD_CALL_AS_(obj, type, meth) SD_AS(obj, type)->meth(SD_AS(obj, type))
#define sd_log_info(fmt, ...)
#define sd_log_debug(fmt, ...)
#define sd_err(reason) sd_err_handler(SD_ERR, __FILE__, __LINE__, (char *) __func__, reason);
Typedefs
typedef enum sd_stat sd_stat
typedef struct sd_rng sd_rng
typedef struct sd_hfill sd_hfill
typedef struct sd_hist sd_hist
typedef void *(* sd_malloc_t) (size_t size)
typedef void *(* sd_realloc_t) (void *ptr, size_t size)
typedef void(* sd_free_t) (void *ptr)
typedef struct sd_sys_in sd_sys_in
typedef struct sd_sys_out sd_sys_out
typedef struct sd_sys sd_sys
typedef struct sd_sys_exc sd_sys_exc
typedef struct sd_net sd_net
typedef struct sd_out sd_out
typedef struct sd_out_file sd_out_file
typedef struct sd_out_mem sd_out_mem
typedef struct sd_out_tee sd_out_tee
typedef struct sd_out_tavg sd_out_tavg
typedef struct sd_out_sfilt sd_out_sfilt
typedef struct sd_sch sd_sch
typedef struct sd_sol sd_sol
typedef int(* sd_log_msg_fp) (const char *fmt,...)
typedef void(* sd_err_handler_fp) (int err, char *file, int line, char *func, char *reason)
Enumerations
enum sd_stat { SD_OK, SD_ERR, SD_CONT, SD_STOP }
Functions
uint32_t sd_ver_major ()
uint32_t sd_ver_minor ()
SD_API sd_stat sd_util_read_square_matrix (const char *fname, uint32_t *n, double **w)
SD_API sd_stat sd_util_uniqi (uint32_t n, uint32_t *restrict ints, uint32_t *restrict nuniq, uint32_t **uints)
SD_API sd_rng * sd_rng_new_default ()
SD_API sd_hfill * sd_hfill_new_val (double val)
SD_API sd_hist * sd_hist_new_default (uint32_t nd, uint32_t *vi, double *vd, double t0, double dt)
SD_API void sd_malloc_set_allocators (sd_malloc_t malloc, sd_realloc_t realloc, sd_free_t free)
SD_API void sd_malloc_set_stdlib_allocators ()
SD_API void * sd_malloc (size_t size)
SD_API void * sd_realloc (void *ptr, size_t size)
SD_API void sd_free (void *ptr)
SD_API sd_sys * sd_sys_new_cb (uint32_t ndim, uint32_t ndc, uint32_t nobs, uint32_t nrpar, uint32_t nipar, void *user_data, sd_stat(*user_apply)(void *, sd_sys_in *, sd_sys_out *))
SD_API sd_sys_exc * sd_sys_exc_new ()
SD_API sd_net * sd_net_new_het (uint32_t n, uint32_t m, uint32_t *restrict M, uint32_t *restrict Ms, uint32_t *restrict Ma, uint32_t *restrict Me, sd_sys **models, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
SD_API sd_net * sd_net_new_hom (uint32_t n, sd_sys *sys, uint32_t ns, uint32_t na, uint32_t ne, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
SD_API sd_sys * sd_roi_new_default (uint32_t n, uint32_t *map)
SD_API sd_out * sd_out_new_cb (void *user_data, sd_stat(*user_apply)(void *, double t, uint32_t nx, double *restrict x, uint32_t nc, double *restrict c))
SD_API sd_out_file * sd_out_file_new_from_name (char *fname)
SD_API sd_out_file * sd_out_file_new_from_std (FILE *std)
SD_API sd_out_mem * sd_out_mem_new ()
SD_API sd_out_tee * sd_out_tee_new (uint32_t nout)
SD_API sd_out_tavg * sd_out_tavg_new (uint32_t len, sd_out *out)
SD_API sd_out_sfilt * sd_out_sfilt_new (uint32_t nfilt, uint32_t filtlen, double *restrict xfilts, double *restrict cfilts, sd_out *out)
SD_API sd_out * sd_out_new_until (double time)
SD_API sd_out * sd_out_ignore (bool ignore_x, bool ignore_c)
SD_API sd_sch * sd_sch_new_cb (uint32_t nx, void *user_data, sd_stat(*user_apply)(void *, sd_hist *, sd_rng *, sd_sys *, double t, double dt, uint32_t nx, double *restrict x, uint32_t nc, double *restrict c))
SD_API sd_sch * sd_sch_new_id (uint32_t nx)
SD_API sd_sch * sd_sch_new_em (uint32_t nx)
SD_API sd_sch * sd_sch_new_emc (uint32_t nx, double lam)
double sd_sch_emcolor_get_lam (sd_sch *sch)
SD_API sd_sch * sd_sch_new_heun (uint32_t nx)
SD_API sd_sol * sd_sol_new_default (sd_sys *sys, sd_sch *scheme, sd_out *out, sd_hfill *hf, uint32_t seed, uint32_t nx, double *restrict x0, uint32_t nce, uint32_t nca, uint32_t *restrict vi, double *restrict vd, double t0, double dt)
SD_API sd_stat sd_sparse_from_dense (uint32_t m, uint32_t n, double *dA, double *dB, double eps, uint32_t *nnz, uint32_t **Or, uint32_t **Ic, double **sA, double **sB)
SD_API sd_log_msg_fp sd_log_get_msg ()
SD_API void sd_log_set_msg (sd_log_msg_fp fp)
SD_API bool sd_log_is_quiet ()
SD_API void sd_log_set_quiet (bool flag)
SD_API bool sd_log_is_verbose ()
SD_API void sd_log_set_verbose (bool flag)
void sd_err_default_handler (int err, char *file, int line, char *func, char *reason)
sd_err_handler_fp sd_err_get_handler ()
void sd_err_set_handler (sd_err_handler_fp fp)
void sd_err_handler (int err, char *file, int line, char *func, char *reason)
Variables
sd_log_msg_fp sd_log_msg
Macro Definition Documentation
#define restrict
Definition at line 40 of file sddekit.h.
#define SD_API
SDDEKit
Definition at line 29 of file sddekit.h.
#define SD_AS (obj, type) (((obj)->type)(obj))
Definition at line 45 of file sddekit.h.
#define SD_CALL_AS (obj, type, meth, ...) SD_AS(obj, type)->meth(SD_AS(obj, type), __VA_ARGS__)
Definition at line 47 of file sddekit.h.
#define SD_CALL_AS_ (obj, type, meth) SD_AS(obj, type)->meth(SD_AS(obj, type))
Definition at line 50 of file sddekit.h.
#define sd_err (reason) sd_err_handler(SD_ERR, __FILE__, __LINE__, (char *) __func__, reason);
Handle an error.
Parameters
reason description of error
Definition at line 1583 of file sddekit.h.
Referenced by sd_hfill_new_val(), sd_hist_new_default(), sd_malloc(), sd_malloc_set_allocators(), sd_net_new_het(), sd_net_new_hom(), sd_out_file_new_from_name(), sd_out_mem_new(), sd_out_new_cb(), sd_out_new_until(), sd_out_sfilt_new(), sd_out_tavg_new(), sd_out_tee_new(), sd_realloc(), sd_rng_new_default(), sd_sch_new_cb(), sd_sch_new_emc(), sd_sch_new_heun(), sd_sol_new_default(), sd_sparse_from_dense(), sd_sys_exc_new(), sd_sys_new_cb(), sd_util_read_square_matrix(), and sd_util_uniqi().
#define sd_log_debug (fmt, ...)
Value:
if (sd_log_is_verbose()) \
    sd_log_msg("[DEBUG] %s:%d (%s) " fmt "\n", __FILE__, __LINE__, __func__, ## __VA_ARGS__)
Definition at line 1538 of file sddekit.h.
Referenced by sd_err_default_handler(), sd_err_handler(), sd_err_set_handler(), and sd_free().
#define sd_log_info (fmt, ...)
Value:
if (!sd_log_is_quiet()) \
    sd_log_msg("[INFO] %s:%d (%s) " fmt "\n", __FILE__, __LINE__, __func__, ## __VA_ARGS__)
Define logging macros differently depending on the compiler being used.
Definition at line 1536 of file sddekit.h.
Referenced by sd_test_report().
Typedef Documentation
typedef void(* sd_err_handler_fp) (int err, char *file, int line, char *func, char *reason)
Typedef for error handler callback.
Parameters
err error number.
file file name where error originates.
line line number in file where error originates.
reason description of error.
Definition at line 1554 of file sddekit.h.
typedef void(* sd_free_t) (void *ptr)
Definition at line 373 of file sddekit.h.
typedef struct sd_hfill sd_hfill
Definition at line 147 of file sddekit.h.
typedef struct sd_hist sd_hist
Definition at line 184 of file sddekit.h.
typedef int(* sd_log_msg_fp) (const char *fmt,...)
Type definition for callback handling formatted messages.
Definition at line 1486 of file sddekit.h.
typedef void*(* sd_malloc_t) (size_t size)
Definition at line 371 of file sddekit.h.
typedef struct sd_net sd_net
Definition at line 633 of file sddekit.h.
typedef struct sd_out sd_out
Definition at line 856 of file sddekit.h.
typedef struct sd_out_file sd_out_file
Definition at line 897 of file sddekit.h.
typedef struct sd_out_mem sd_out_mem
Definition at line 948 of file sddekit.h.
typedef struct sd_out_sfilt sd_out_sfilt
Definition at line 1136 of file sddekit.h.
typedef struct sd_out_tavg sd_out_tavg
Interface for temporal average out.
Definition at line 1083 of file sddekit.h.
typedef struct sd_out_tee sd_out_tee
Definition at line 1019 of file sddekit.h.
typedef void*(* sd_realloc_t) (void *ptr, size_t size)
Definition at line 372 of file sddekit.h.
typedef struct sd_rng sd_rng
Definition at line 105 of file sddekit.h.
typedef struct sd_sch sd_sch
Definition at line 1218 of file sddekit.h.
typedef struct sd_sol sd_sol
Definition at line 1333 of file sddekit.h.
typedef enum sd_stat sd_stat
Status codes used by various functions.
typedef struct sd_sys sd_sys
Definition at line 454 of file sddekit.h.
typedef struct sd_sys_exc sd_sys_exc
Definition at line 517 of file sddekit.h.
typedef struct sd_sys_in sd_sys_in
typedef struct sd_sys_out sd_sys_out
Enumeration Type Documentation
enum sd_stat
Status codes used by various functions.
Enumerator
SD_OK
Function call succeeded
SD_ERR
An error occurred during the function call or one of the functions it called.
SD_CONT
Returned by output object to indicate solver should continue
SD_STOP
Returned by output object to indicate solver should stop
Definition at line 61 of file sddekit.h.
                      {
     SD_OK,
     SD_ERR,
     SD_CONT,
     SD_STOP
 } sd_stat;
Function Documentation
void sd_err_default_handler (int err, char * file, int line, char * func, char * reason)
The default error handler logs the error in the debug log.
Definition at line 5 of file sd_err.c.
References sd_log_debug.
 {
     (void) err;
     sd_log_debug("%s raised error at %s:%d `%s'.", func, file, line, reason);
 }
sd_err_handler_fp sd_err_get_handler ()
Get the current error handler.
Definition at line 13 of file sd_err.c.
References sd_err_handler().
 { return sd_err_handler; }
void sd_err_handler (int err, char * file, int line, char * func, char * reason)
Dispatches error to current error handler.
Definition at line 21 of file sd_err.c.
References sd_log_debug.
Referenced by sd_err_get_handler().
{
     if (handler!=NULL)
         (*handler)(err, file, line, func, reason);
 #ifdef SDDEBUG
     else
         sd_log_debug("%s raised error at %s:%d `%s' (ignored by null handler).", func, file, line, reason);
 #endif
 }
void sd_err_set_handler (sd_err_handler_fp fp)
Set the current error handler.
Parameters
fp new handler. if NULL, errors will be unhandled.
Definition at line 15 of file sd_err.c.
References sd_log_debug.
{
     if (fp==NULL)
         sd_log_debug("set NULL error handler.");
     handler = fp;
 }
SD_API void sd_free (void * ptr)
Free memory using current allocator.
Definition at line 43 of file sd_malloc.c.
References sd_log_debug.
Referenced by one_step_free(), sd_hist_new_default(), sd_net_new_hom(), sd_out_sfilt_new(), sd_out_tee_new(), sd_rng_new_default(), sd_sch_new_emc(), sd_sch_new_heun(), sd_sol_new_default(), sd_sparse_from_dense(), sd_util_uniqi(), and sfilt_free().
{
 #ifdef SDDEBUGFREE
     static int n = 0;
 #endif
     if (ptr==NULL) {
         sd_log_debug( "[sd_free] cowardly refusing to free a NULL pointer." );
         return;
     }
 #ifdef SDDEBUGFREE
     sd_log_debug("%d'th call to sd_free on %p.", n, ptr);
     n++;
 #endif
     (*_sd_free)(ptr);
 }
SD_API sd_hfill* sd_hfill_new_val (double val)
An sd_hfill instance which sets all elements of the history buffer to a given value.
Definition at line 406 of file sd_hist.c.
References sd_hfill::apply, sd_hfill::free, sd_hfill::ptr, sd_err, and sd_malloc().
 {
     sd_hfill *hf;
     if ((hf=sd_malloc(sizeof(sd_hfill))) == NULL
         || (hf->ptr=sd_malloc(sizeof(double))) == NULL)
     {
         sd_err("alloc hfill failed.");
         return hf;
     }
     *((double*)hf->ptr) = val;
     hf->free = &val_fill_free;
     hf->apply = &val_fill_apply;
     return hf;
 }
SD_API sd_hist* sd_hist_new_default (uint32_t nd, uint32_t * vi, double * vd, double t0, double dt)
Initialize an history instance.
Parameters
h an allocated history instance.
nd number of delayed coupling terms.
vi efferent index of each delayed coupling term.
vd delay of each delayed coupling term.
t0 starting time.
dt time-step to use in history buffer (need not equal solution dt).
Returns
initialized history instance or NULL if error occurs.
Definition at line 353 of file sd_hist.c.
References hist_data::buf, hist_data::del, hist_data::dt, hist_data::lim, hist_data::nd, hist_data::nu, sd_hist::ptr, sd_err, sd_free(), sd_malloc(), SD_OK, sd_util_uniqi(), hist_data::t, hist_data::uvi, and hist_data::vi.
Referenced by sd_sol_new_default().
 {
     sd_hist *hist;
     hist_data *h = NULL, zh = { 0 };
     if ((hist = sd_malloc(sizeof(sd_hist))) == NULL
         || (h = hist->ptr = sd_malloc(sizeof(hist_data))) == NULL
         || (*h = zh, (h->nd = nd) < 1)
         || sd_util_uniqi(nd, vi, &(h->nu), &(h->uvi)) != SD_OK
         || (h->del = sd_malloc(sizeof(double) * nd)) == NULL
         || (h->vi = sd_malloc(sizeof(uint32_t) * nd)) == NULL
         || (memcpy(h->del, vd, nd * sizeof(double)),
             memcpy(h->vi, vi, nd * sizeof(uint32_t)),
             0)
         || setup_buffer_structure(h, dt) != SD_OK
         || (h->buf = sd_malloc(sizeof(double) * h->lim[h->nu])) == NULL
         )
     {
         if (hist != NULL) sd_free(hist);
         if (h != NULL)
         {
             if (h->buf!=NULL) sd_free(h->buf);
             if (h->uvi!=NULL) sd_free(h->uvi);
             if (h->del!=NULL) sd_free(h->del);
             if (h->vi!=NULL) sd_free(h->vi);
         }
         sd_err("number of delays < 1 or memory alloc failed.");
         return NULL;
     }
     h->dt = dt;
     h->t = t0;
     *hist = sd_hist_defaults;
     hist->ptr = h;
     return hist;
 }
SD_API sd_log_msg_fp sd_log_get_msg ()
Get function pointer handling messages.
Definition at line 10 of file sd_log.c.
References sd_log_msg.
 {
     return sd_log_msg;
 }
SD_API bool sd_log_is_quiet ()
Get status of quiet flag.
Definition at line 20 of file sd_log.c.
 {
     return sd_log_quiet;
 }
SD_API bool sd_log_is_verbose ()
Get status of verbose flag.
Definition at line 32 of file sd_log.c.
 {
     return sd_log_verbose;
 }
SD_API void sd_log_set_msg (sd_log_msg_fp fp)
Set function pointer handling messages.
Definition at line 15 of file sd_log.c.
References sd_log_msg.
 {
     sd_log_msg = fp;
 }
SD_API void sd_log_set_quiet (bool flag)
Set status of quiet flag.
Definition at line 25 of file sd_log.c.
 {
     sd_log_quiet = flag;
     if (flag)
         sd_log_verbose = 0;
 }
SD_API void sd_log_set_verbose (bool flag)
Set status of verbose flag.
Definition at line 37 of file sd_log.c.
 {
     sd_log_verbose = flag;
     if (flag)
         sd_log_quiet = 0;
 }
SD_API void* sd_malloc (size_t size)
Allocate memory using current allocator.
Definition at line 27 of file sd_malloc.c.
References sd_err.
Referenced by sd_hfill_new_val(), sd_hist_new_default(), sd_net_new_het(), sd_net_new_hom(), sd_out_mem_new(), sd_out_new_cb(), sd_out_new_until(), sd_out_sfilt_new(), sd_out_tavg_new(), sd_out_tee_new(), sd_rng_new_default(), sd_sch_new_cb(), sd_sch_new_emc(), sd_sch_new_heun(), sd_sol_new_default(), sd_sparse_from_dense(), sd_sys_exc_new(), sd_sys_new_cb(), sd_util_read_square_matrix(), and sd_util_uniqi().
{
     void *new_ptr;
     new_ptr = (*_sd_malloc)(size);
     if (new_ptr==NULL)
         sd_err( "[sd_alloc] alloc returned a NULL pointer." );
     return new_ptr;
 }
SD_API void sd_malloc_set_allocators (sd_malloc_t malloc, sd_realloc_t realloc, sd_free_t free)
Set custom allocators to be used whenever sd_ calls require allocating or freeing memory.
Definition at line 13 of file sd_malloc.c.
References sd_err.
Referenced by sd_malloc_set_stdlib_allocators().
{
     if (malloc == NULL || realloc == NULL || free == NULL) {
         sd_err( "sd_malloc_set_allocators passed a NULL allocator." );
         return;
     }
     _sd_malloc = malloc;
     _sd_realloc = realloc;
     _sd_free = free;
 }
SD_API void sd_malloc_set_stdlib_allocators ()
Set allocators to stdlib functions (malloc, realloc, free)
Definition at line 23 of file sd_malloc.c.
References sd_malloc_set_allocators().
{
     sd_malloc_set_allocators(&malloc, &realloc, &free);
 }
SD_API sd_net* sd_net_new_het (uint32_t n, uint32_t m, uint32_t *restrict M, uint32_t *restrict Ms, uint32_t *restrict Ma, uint32_t *restrict Me, sd_sys ** models, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
Create new instance of default network implementation.
Init network for general case of heterogeneous network of nm different models
Note
Further use requires filling data structures.
Parameters
d network to initialize.
n number of nodes in network.
m number of models used in network.
nnz number of non-zero elements in weights matrix.
w array of non-zero elements of weights matrix.
d array of delays per non-zero weight.
Returns
0 on success, 1 if error occurred.
Definition at line 181 of file sys_net.c.
References netd::_init1, netd::cn, netd::d, netd::Ic, netd::m, netd::M, M, netd::Ma, netd::Me, netd::models, netd::Ms, netd::n, netd::ne, netd::net_if, netd::nnz, netd::ns, netd::Or, sd_sys::ptr, sd_net::ptr, sd_err, sd_malloc(), netd::sys_if, and netd::w.
Referenced by sd_net_new_hom().
 {
     uint32_t i;
     netd *net = sd_malloc(sizeof(netd));
     if (net == NULL)
     {
         sd_err("net alloc failed.");
         return NULL;
     }
     net->net_if = net_defaults;
     net->sys_if = net_sys_defaults;
     net->net_if.ptr = net->sys_if.ptr = net;
     net->n = n;
     net->m = m;
     net->nnz = nnz;
     net->M = M;
     net->Ms = Ms;
     net->Ma = Ma;
     net->Me = Me;
     net->models = models;
     net->Or = Or;
     net->Ic = Ic; /* TODO ? same as Ie ? */
     net->w = w;
     net->d = d;
     /* intialize based on passed attributes: Ie, cne, cna */
     net->ns = 0;
     net->ne = 0;
     for (i=0; i<n; i++) {
         net->ns += net->Ms[net->M[i]];
         net->ne += net->Me[net->M[i]];
     }
     if ((net->cn = sd_malloc (sizeof(double) * net->ne))==NULL)
     {
         sd_err("failed to allocate memory for network.");
         return NULL;
     }
     net->_init1 = 0;
     return &(net->net_if);
 }
SD_API sd_net* sd_net_new_hom (uint32_t n, sd_sys * sys, uint32_t ns, uint32_t na, uint32_t ne, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
Init network for homogeneous model case where m==1, simplifying setup.
Parameters
net network to initialize.
n number of nodes in network.
sys model system to use.
data user data for system.
ns number of state variables for system.
na number of afferent terms for system.
ne number of efferent terms for system.
nnz number of non-zero elements in weights matrix.
Or array of row offsets in non-zero arrays.
Ic array of column indices in non-zero arrays.
w array of non-zero elements of weights matrix.
d array of delays per non-zero weight.
Definition at line 72 of file sys_net.c.
References M, sd_net::ptr, sd_err, sd_free(), sd_malloc(), and sd_net_new_het().
 {
     uint32_t i, *M, *Ms, *Me, *Ma;
     sd_sys **models;
     char *errmsg;
     sd_net *net;
     M = Ms = Me = Ma = NULL;
     models = NULL;
     if ((M = sd_malloc (sizeof(uint32_t) * n))==NULL
      || (Ms = sd_malloc (sizeof(uint32_t)))==NULL
      || (Ma = sd_malloc (sizeof(uint32_t)))==NULL
      || (Me = sd_malloc (sizeof(uint32_t)))==NULL
      || (models = sd_malloc (sizeof(sd_sys*)))==NULL)
     {
         errmsg = "failed to allocate net init1 storage.";
         goto fail;
     }
     Ms[0] = ns;
     Ma[0] = na;
     Me[0] = ne;
     for(i=0; i<n; i++)
         M[i] = 0;
     models[0] = sys;
     if ((net = sd_net_new_het(n, 1, M, Ms, Ma, Me, models,
                     nnz, Or, Ic, w, d)) == NULL)
     {
         errmsg = "net initn failed.";
         goto fail;
     }
     ((netd*)net->ptr)->_init1 = true;
     return net;
 fail:
     if (M!=NULL) sd_free(M);
     if (Ms!=NULL) sd_free(Ms);
     if (Me!=NULL) sd_free(Me);
     if (Ma!=NULL) sd_free(Ma);
     if (models!=NULL) sd_free(models);
     sd_err(errmsg);
     return NULL;
 }
SD_API sd_out_file* sd_out_file_new_from_name (char * fname)
Create a new file output for file name.
Parameters
d file output instance.
fname path to file with write permissions.
Definition at line 87 of file out_file.c.
References sd_err.
 {
     FILE *file;
     if ((file = fopen(fname, "w"))==NULL)
     {
         sd_err("unable to open file for writing.");
         return NULL;
     }
     return sd_out_file_new(file, false);
 }
SD_API sd_out_file* sd_out_file_new_from_std (FILE * std)
Initialize file output from stdout or stderr.
Parameters
d file output instance.
std stdout or stderr.
Definition at line 99 of file out_file.c.
 {
     return sd_out_file_new(std, true);
 }
SD_API sd_out* sd_out_ignore (bool ignore_x, bool ignore_c)
Create new out for ignoring x or c.
SD_API sd_out_mem* sd_out_mem_new ()
Create new output memory buffer.
Definition at line 126 of file out_mem.c.
References mem_data::capacity, mem_data::cs, mem_data::mem_if, mem_data::n_sample, mem_data::out_if, sd_out::ptr, sd_out_mem::ptr, sd_err, sd_malloc(), and mem_data::xs.
 {
     mem_data *d = NULL;
     if ((d = sd_malloc(sizeof(mem_data))) == NULL)
     {
         sd_err("alloc failed for new mem output.");
         return NULL;
     }
     d->xs = NULL;
     d->cs = NULL;
     d->n_sample = 0;
     d->capacity = 0;
     d->mem_if = mem_defaults;
     d->out_if = mem_out_defaults;
     d->out_if.ptr = d->mem_if.ptr = d;
     return &(d->mem_if);
 }
SD_API sd_out* sd_out_new_cb (void * user_data, sd_stat(*)(void *, double t, uint32_t nx, double *restrict x, uint32_t nc, double *restrict c) user_apply)
Create new out based on user provided data & callback.
Definition at line 34 of file out_cb.c.
References data::out, sd_out::ptr, sd_err, sd_malloc(), data::user_apply, and data::user_data.
 {
     data *d;
         if ((d = sd_malloc(sizeof(data))) == NULL)
     {
         sd_err("alloc out cb failed.");
         return NULL;
     }
     d->out = defaults;
     d->out.ptr = d;
     d->user_data = user_data;
     d->user_apply = user_apply;
     return &(d->out);
 }
SD_API sd_out* sd_out_new_until (double time)
Create new out for stopping after certain time.
Definition at line 32 of file out_until.c.
References data::out, sd_out::ptr, sd_err, sd_malloc(), and data::time.
 {
     data *d;
         if ((d = sd_malloc(sizeof(data))) == NULL)
     {
         sd_err("alloc out until failed.");
         return NULL;
     }
     d->out = defaults;
     d->out.ptr = d;
     d->time = time;
     return &(d->out);
 }
SD_API sd_out_sfilt* sd_out_sfilt_new (uint32_t nfilt, uint32_t filtlen, double *restrict xfilts, double *restrict cfilts, sd_out * out)
Create instance of spatial filter output.
Parameters
nfilt number of spatial filters
filtlen length of filter coefficients.
xfilts filter coefficients for state variablex.
cfilts filter coefficients for coupling variables.
out output callback to pass filtered data to.
Definition at line 74 of file out_sfilt.c.
References sfiltd::c, sfiltd::cfilts, sfiltd::filtlen, sfiltd::next_out, sfiltd::nfilt, sfiltd::out, sd_out::ptr, sd_out_sfilt::ptr, sd_err, sd_free(), sd_malloc(), sfiltd::sfilt, sfiltd::x, and sfiltd::xfilts.
 {
     uint32_t n_filt_bytes;
     sfiltd *d, zd = { 0 };
     n_filt_bytes = nfilt * filtlen * sizeof(double);
     if ((d = sd_malloc(sizeof(sfiltd))) == NULL
         || (*d = zd, nfilt < 1 || filtlen < 1)
         || (d->out = sd_malloc(sizeof(sd_out))) == NULL
         || (d->sfilt = sd_malloc(sizeof(sd_out_sfilt))) == NULL
         || (d->xfilts = sd_malloc(n_filt_bytes)) == NULL
         || (d->cfilts = sd_malloc(n_filt_bytes)) == NULL
         || (d->x = sd_malloc(sizeof(double) * nfilt)) == NULL
         || (d->c = sd_malloc(sizeof(double) * nfilt)) == NULL
         )
     {
         if (d->xfilts!=NULL) sd_free(d->xfilts);
         if (d->cfilts!=NULL) sd_free(d->cfilts);
         if (d->x!=NULL) sd_free(d->x);
         if (d->sfilt != NULL) sd_free(d->sfilt);
         if (d->out != NULL) sd_free(d->out);
         sd_free(d);
         sd_err("nfilt < 1, filtlen < 1 or memory alloc failed.");
         return NULL;
     }
     d->nfilt = nfilt;
     d->filtlen = filtlen;
     memcpy(d->xfilts, xfilts, n_filt_bytes);
     memcpy(d->cfilts, cfilts, n_filt_bytes);
     d->next_out = next_out;
     *(d->out) = sfilt_out_defaults;
     *(d->sfilt) = sfilt_defaults;
     d->out->ptr = d->sfilt->ptr = d;
     return d->sfilt;
 }
SD_API sd_out_tavg* sd_out_tavg_new (uint32_t len, sd_out * out)
Create instance of temporal average output.
Parameters
len number of samples used for averagng.
out output to pass averaged data to.
Definition at line 110 of file out_tavg.c.
References tavg::len, tavg::next_out, tavg::out_if, sd_out::ptr, sd_out_tavg::ptr, sd_err, sd_malloc(), and tavg::tavg_if.
 {
     tavg *d, z = { 0 };
     if ((d = sd_malloc(sizeof(tavg))) == NULL
         || (*d = z, d->next_out = next_out, 0))
     {
         sd_err("alloc fail or NULL next_out.");
         return NULL;
     }
     d->out_if = tavg_out_defaults;
     d->tavg_if = tavg_defaults;
     d->out_if.ptr = d->tavg_if.ptr = d;
     d->len = len;
     return &(d->tavg_if);
 }
SD_API sd_out_tee* sd_out_tee_new (uint32_t nout)
Create instance of output splitter.
Parameters
nout number of outputs to distribute to.
Definition at line 79 of file out_tee.c.
References tee_data::nout, tee_data::out, tee_data::outs, sd_out::ptr, sd_out_tee::ptr, sd_err, sd_free(), sd_malloc(), and tee_data::tee.
 {
     tee_data *d, zd = { 0 };
     if ((d = sd_malloc(sizeof(tee_data))) == NULL
         || (*d = zd, 0)
         || (d->outs = sd_malloc(sizeof(sd_out) * nout)) == NULL
         || (d->out = sd_malloc(sizeof(sd_out))) == NULL
         || (d->tee = sd_malloc(sizeof(sd_out_tee))) == NULL)
     {
         if (d != NULL)
         {
             if (d->out!=NULL) sd_free(d->out);
             if (d->outs!=NULL) sd_free(d->outs);
             sd_free(d);
         }
         sd_err("alloc for tee failed.");
         return NULL;
     }
     d->nout = nout;
     *(d->out) = tee_out_defaults;
     *(d->tee) = tee_defaults;
     d->tee->ptr = d->out->ptr = d;
     return d->tee;
 }
SD_API void* sd_realloc (void * ptr, size_t size)
Allocate memory using current allocator.
Definition at line 35 of file sd_malloc.c.
References sd_err.
{
     void *new_ptr;
     new_ptr = (*_sd_realloc)(ptr, size);
     if (new_ptr==NULL)
         sd_err( "[sd_realloc] realloc returned a NULL pointer." );
     return new_ptr;
 }
SD_API sd_rng* sd_rng_new_default ()
Construct a new RNG from default implementation.
Definition at line 56 of file sd_rng.c.
References sd_rng::ptr, sd_err, sd_free(), and sd_malloc().
Referenced by sd_sol_new_default().
 {
     sd_rng *r, z = { 0 };
     if ((r = sd_malloc (sizeof(sd_rng))) == NULL
      || (*r = rng_default, 0)
      || (r->ptr = sd_malloc (sizeof(struct rng_data))) == NULL)
     {
         sd_free(r);
         sd_err("alloc rng failed.");
         return NULL;
     }
     return r;
 }
SD_API sd_sys* sd_roi_new_default (uint32_t n, uint32_t * map)
Create new instance of default region mapping / regions of interest.
double sd_sch_emcolor_get_lam (sd_sch * sch)
Get the current value of lambda, the characteristic decorrelation time.
Note
Argument sch MUST be an instance of sd_sch created by sd_sch_new_emc.
Parameters
sch scheme instance.
Returns
current value of lambda.
SD_API sd_sch* sd_sch_new_cb (uint32_t nx, void * user_data, sd_stat(*)(void *, sd_hist *, sd_rng *, sd_sys *, double t, double dt, uint32_t nx, double *restrict x, uint32_t nc, double *restrict c) user_apply)
Create new scheme based on user-provided data & callback.
Definition at line 40 of file sch_cb.c.
References sd_sch::ptr, data::sch, sd_err, sd_malloc(), data::user_apply, and data::user_data.
 {
     data *d;
         if ((d = sd_malloc(sizeof(data))) == NULL)
     {
         sd_err("alloc sch cb failed.");
         return NULL;
     }
     d->sch = defaults;
     d->sch.ptr = d;
     d->user_data = user_data;
     d->user_apply = user_apply;
     return &(d->sch);
 }
SD_API sd_sch* sd_sch_new_em (uint32_t nx)
Definition at line 116 of file sd_scheme.c.
 {
     sd_sch *new = new_one_step(nx);
     new->apply = &em_apply;
     return new;
 }
SD_API sd_sch* sd_sch_new_emc (uint32_t nx, double lam)
Definition at line 191 of file sd_scheme.c.
References sd_sch::apply, emc_data::eps, emc_data::f, emc_data::first_call, sd_sch::free, emc_data::g, sd_sch::get_nx, emc_data::lam, emc_data::nx, sd_sch::ptr, sd_err, sd_free(), sd_malloc(), and emc_data::z.
 {
     bool err;
     emc_data *d;
     sd_sch *sch;
     if ((d = sd_malloc(sizeof(emc_data))) == NULL) {
         sd_err("memory alloc for one step sch failed.");
         return NULL;
     }
     {
         emc_data zero = { 0 };
         *d = zero;
     }
     d->nx = nx;
     err = (sch = sd_malloc(sizeof(sd_sch))) == NULL;
     err |= (d->f=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->g=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->z=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->eps=sd_malloc(sizeof(double)*nx))==NULL;
     if (err) {
         if (d->f!=NULL) sd_free(d->f);
         if (d->g!=NULL) sd_free(d->g);
         if (d->z!=NULL) sd_free(d->z);
         if (d->eps!=NULL) sd_free(d->eps);
         if (d != NULL) sd_free(d);
         if (sch != NULL) sd_free(sch);
         sd_err("memory alloc for sch em color failed.");
         return NULL;
     }
     d->first_call = true;
     d->lam = lam;
     sch->ptr = d;
     sch->get_nx = &emc_get_nx;
     sch->apply = &emc_apply;
     sch->free = &emc_free;
     return sch;
 }
SD_API sd_sch* sd_sch_new_heun (uint32_t nx)
Definition at line 291 of file sd_scheme.c.
References sd_sch::apply, heun_data::fl, heun_data::fr, sd_sch::free, sd_sch::get_nx, heun_data::gl, heun_data::gr, heun_data::nx, sd_sch::ptr, sd_err, sd_free(), sd_malloc(), heun_data::xr, and heun_data::z.
 {
     bool err;
     heun_data *d;
     sd_sch *sch;
     if ((d = sd_malloc(sizeof(heun_data))) == NULL)
     {
         sd_err("memory alloc for heun scheme failed.");
         return NULL;
     }
     {
         heun_data zero = { 0 };
         *d = zero;
     }
     d->nx = nx;
     err = (sch = sd_malloc(sizeof(sd_sch)))==NULL;
     err |= (d->fl=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->fr=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->gl=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->gr=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->z=sd_malloc(sizeof(double)*nx))==NULL;
     err |= (d->xr=sd_malloc(sizeof(double)*nx))==NULL;
     if (err) {
         if (d->fl!=NULL) sd_free(d->fl);;
         if (d->fr!=NULL) sd_free(d->fr);;
         if (d->gl!=NULL) sd_free(d->gl);;
         if (d->gr!=NULL) sd_free(d->gr);;
         if (d->z!=NULL) sd_free(d->z);;
         if (d->xr!=NULL) sd_free(d->xr);;
         if (d != NULL) sd_free(d);
         if (sch != NULL) sd_free(sch);
         sd_err("memory alloc durong sch em init failed.");
         return NULL;
     }
     sch->ptr = d;
     sch->get_nx = &heun_get_nx;
     sch->apply = &heun_apply;
     sch->free = &heun_free;
     return sch;
 }
SD_API sd_sch* sd_sch_new_id (uint32_t nx)
Create instance of the identity scheme
The identity schemes updates the state following f & g directly, i.e.
x_{t+1} = f(x_t) + g(x_t) * z
This is useful for difference equations, for example.
Parameters
d allocated scheme instance.
nx number of state variables.
Definition at line 109 of file sd_scheme.c.
 {
     sd_sch *new = new_one_step(nx);
     new->apply = &id_apply;
     return new;
 }
SD_API sd_sol* sd_sol_new_default (sd_sys * sys, sd_sch * scheme, sd_out * out, sd_hfill * hf, uint32_t seed, uint32_t nx, double *restrict x0, uint32_t nce, uint32_t nca, uint32_t *restrict vi, double *restrict vd, double t0, double dt)
Create a new default solver instance.
Parameters
sys system to be integrated.
scheme time-stepping scheme to use for solution.
out output handler.
hf history filler.
seed seed for random number generation.
nx number of state variables.
x0 initial state at t = 0.
nce number of coupling variables emit by system.
nca number of coupling variables accpted by system.
vi indices of coupling variables (length nca).
vd delays of coupling variables (length nca, strictly positive).
t0 starting time.
dt time step.
Definition at line 77 of file sd_solv.c.
References sol_data::c, sol_data::cont, sol_data::dt, FAILIF, sd_hist::fill, sd_hist::free, sol_data::hf, sol_data::hist, sol_data::nca, sol_data::nce, sol_data::nx, sol_data::out, sd_sol::ptr, sol_data::rng, sol_data::sch, sd_err, sd_free(), sd_hist_new_default(), sd_malloc(), SD_OK, sd_rng_new_default(), sd_rng::seed, sol_data::sys, sol_data::t, sol_data::x, and sol_data::x0.
 {
     char *errmsg;
     sd_sol *sol = NULL;
     /* error handling */
 #define FAILIF(cond, msg)\
         if (cond) { \
         errmsg = msg;\
         goto uhoh;\
     }
     /* allocate & zero sol interface & data */
     {
         sol_data zdat = { 0 };
         FAILIF((sol = sd_malloc(sizeof(sd_sol)))==NULL, "allocating solver failed.");
         *sol = sol_default;
         FAILIF((sol->ptr = sd_malloc(sizeof(sol_data)))==NULL, "allocating solver data failed.");
         *((sol_data*) sol->ptr) = zdat;
         /* TODO fill interface table */
     }
     FAILIF(sys == NULL || scheme == NULL || hf == NULL || out == NULL,
         "cannot initialize solver with NULL system, scheme, out or history function.")
     /* copy arguments */
     {
         sol_data *s = (sol_data*)sol->ptr;
         s->nx = nx;
         s->nce = nce;
         s->nca = nca;
         s->cont = 1;
         s->sys = sys;
         s->sch = scheme;
         s->out = out;
         s->hf = hf;
     }
     /* setup coupling */
     {
         sol_data *s = (sol_data*)sol->ptr;
         if (nca > 0 && vi!=NULL && vd!=NULL)
             {
                 size_t cn;
                 FAILIF((s->hist = sd_hist_new_default(nca, vi, vd, t0, dt)) == NULL, "failed to create history.")
                 FAILIF(s->hist->fill(s->hist, hf)!=SD_OK, "history fill failed.")
                 /* s->c big enough to accomate aff or eff */
                 cn = nca > nce ? nca : nce;
                 FAILIF((s->c = sd_malloc(sizeof(double) * cn)) == NULL, "alloc coupling array failed.")
         } else {
             s->nca = 0;
             s->c = NULL;
         }
     }
     /* initial conditions */
     {
         sol_data *s = (sol_data*)sol->ptr;
         FAILIF((s->rng = sd_rng_new_default())==NULL,
             "couldn't create a new rng");
         s->rng->seed(s->rng, seed);
         FAILIF((s->x = sd_malloc (sizeof(double) * nx))==NULL,
                 "failed to alloc solver x")
         FAILIF((s->x0 = sd_malloc (sizeof(double) * nx))==NULL,
             "failed to alloc solver x0")
         memcpy(s->x, x0, sizeof(double) * s->nx);
         memcpy(s->x0, x0, sizeof(double) * s->nx);
         s->t = t0;
         s->dt = dt;
     }
     return sol;
 uhoh:
     /* clean up */
     {
         if (sol != NULL && sol->ptr != NULL)
         {
             sol_data *s = sol->ptr;
             if (s->x!=NULL) sd_free(s->x);
             if (s->x0!=NULL) sd_free(s->x0);
             if (s->c!=NULL) sd_free(s->c);
             if (s->hist!=NULL) s->hist->free(s->hist);
         }
         if (sol != NULL)
             sd_free(sol);
     }
     sd_err(errmsg);
     return NULL;
 }
SD_API sd_stat sd_sparse_from_dense (uint32_t m, uint32_t n, double * dA, double * dB, double eps, uint32_t * nnz, uint32_t ** Or, uint32_t ** Ic, double ** sA, double ** sB)
Create CSR format sparse matrix from dense matrix, possibly thresholding.
Caller responsible for freeing Or, Ic, sA when done.
Parameters
[in] m number of rows.
[in] n number of cols.
[in] dA elements of dense matrix.
[in] dB elements of second dense matrix (can be null).
[in] eps absolute threshold to consider element non-zero (can be 0.0 for no . thresholding).
[out] nnz number of non-zeros.
[out] Or row offsets.
[out] Ic column indices.
[out] sA non-zeros elements of dA.
[out] sB non-zeros elements of dB. (is dB is null, this is unused).
Returns
SD_OK if conversion succeeds, SD_ERR if error occurred.
Definition at line 5 of file sd_sparse.c.
References DO_IF, sd_err, sd_free(), and sd_malloc().
 {
     uint32_t i, j, ci, nm;
     char *errmsg;
     nm = n * m;
     /* count non-zeros*/
     *nnz = 0;
 #define DO_IF(cond) for (i=0; i<nm; i++) if (cond) *nnz += 1
     if (eps==0.0) {
         DO_IF(dA[i]!=0.0);
     } else {
         DO_IF(fabs(dA[i])>eps);
     }
 #undef DO_IF
     /* alloc */
     *Or = sd_malloc (sizeof(uint32_t)*(m + 1));
     *Ic = sd_malloc (sizeof(uint32_t)**nnz);
     *sA = sd_malloc (sizeof(double)**nnz);
     if (dB!=NULL)
         *sB = sd_malloc (sizeof(double)**nnz);
     if (Or==NULL || Ic==NULL || sA==NULL || (dB!=NULL && sB==NULL)) {
         errmsg = "failed to allocate memory for sparse storage.";
         goto fail;
     }
     /* copy elements */
 #define DO_IF(cond)\
         ci = 0;\
         for (i=0; i<m; i++) {\
             (*Or)[i] = ci;\
             for (j=0; j<n; j++) {\
                 if (cond) {\
                     (*Ic)[ci] = j;\
                     (*sA)[ci] = dA[i*m+j];\
                     if (dB!=NULL)\
                         (*sB)[ci] = dB[i*m+j];\
                     ci += 1;\
                 }\
             }\
         }\
         (*Or)[m] = ci
     if (eps==0.0) {
         DO_IF(dA[i*m+j]!=0.0);
     } else {
         DO_IF(fabs(dA[i*m+j])>eps);
     }
 #undef DO_IF
     return 0;
 fail:
     if (*Or!=NULL) sd_free(*Or);
     if (*Ic!=NULL) sd_free(*Ic);
     if (*sA!=NULL) sd_free(*sA);
     if (dB!=NULL)
         if (*sB!=NULL) sd_free(*sB);
     sd_err(errmsg);
     return 1;
 }
SD_API sd_sys_exc* sd_sys_exc_new ()
Create new instance of the Excitator system.
Definition at line 81 of file sys_exc.c.
References exc_default, data::exc_if, data::pars, pars_default, sd_sys::ptr, sd_sys_exc::ptr, sd_err, sd_malloc(), sys_default, and data::sys_if.
{
     struct data *d, zero = {0};
     if ((d = sd_malloc (sizeof(struct data))) == NULL)
     {
         sd_err("alloc exc sys failed.");
         return NULL;
     }
     *d = zero;
     d->pars = pars_default;
     d->sys_if = sys_default;
     d->exc_if = exc_default;
     d->sys_if.ptr = d->exc_if.ptr = d;
     return &(d->exc_if);
 }
SD_API sd_sys* sd_sys_new_cb (uint32_t ndim, uint32_t ndc, uint32_t nobs, uint32_t nrpar, uint32_t nipar, void * user_data, sd_stat(*)(void *, sd_sys_in *, sd_sys_out *) user_apply)
Create new system based on user provided data & callback.
Definition at line 38 of file sys_cb.c.
References data::ndc, ndc(), data::ndim, ndim(), data::nipar, nipar(), data::nobs, nobs(), data::nrpar, nrpar(), sd_sys::ptr, sd_err, sd_malloc(), data::sys, data::user_apply, and data::user_data.
 {
     data *d;
         if ((d = sd_malloc(sizeof(data))) == NULL)
     {
         sd_err("alloc sys cb failed.");
         return NULL;
     }
     d->ndim = ndim;
     d->ndc = ndc;
     d->nobs = nobs;
     d->nrpar = nrpar;
     d->nipar = nipar;
     d->sys = defaults;
     d->sys.ptr = d;
     d->user_data = user_data;
     d->user_apply = user_apply;
     return &(d->sys);
 }
SD_API sd_stat sd_util_read_square_matrix (const char * fname, uint32_t * n, double ** w)
Read a square matrix from file in ascii format into w.
Note
w must be freed by user.
Parameters
[in] fname string containing filename to readable file.
[out] n number of rows & cols.
[out] w matrix of weights.
Returns
SD_OK if succeeds, SD_ERR if error occurs..
Definition at line 65 of file sd_util.c.
References SD_ERR, sd_err, sd_malloc(), and SD_OK.
 {
     uint32_t nn;
     FILE *fd;
     double _, *wi;
     /* open file */
     fd = fopen(fname, "r");
     if (fd==NULL) {
         sd_err("failed to open file");
         return SD_ERR;
     }
     /* count number of readable elements */
     nn = 0;
     {
         int count;
         while (1) {
             count = fscanf(fd, "%lg", &_);
             if (count < 1)
                 break;
             nn++;
         }
     }
     rewind(fd);
     /* setup memory */
     *n = (uint32_t) sqrt(nn);
     wi = sd_malloc (sizeof(double)*nn);
     *w = wi;
     if (wi==NULL) {
         fclose(fd);
         return SD_ERR;
     }
     /* read data into memory this time */
     {
         int count;
         while (1) {
             count = fscanf(fd, "%lg", wi++);
             if (count < 1)
                 break;
         }
     }
     fclose(fd);
     return SD_OK;
 }
SD_API sd_stat sd_util_uniqi (uint32_t n, uint32_t *restrict ints, uint32_t *restrict nuniq, uint32_t ** uints)
Obtain unique sorted integers.
Note
Caller must free uints when done.
Parameters
n number of elements
ints array of at least n integers.
[out] nuniq address of number of unique integers.
[out] uints address of array of unique integers.
Returns
Returns SD_OK if call succeeds, SD_ERR if error occurs.
Definition at line 12 of file sd_util.c.
References SD_ERR, sd_err, sd_free(), sd_malloc(), and SD_OK.
Referenced by sd_hist_new_default().
 {
     uint32_t i, j, *ints_copy;
     if (n==0) return SD_OK;
     if (n==1) {
         *nuniq = 1;
         if ((*uints = sd_malloc (sizeof(uint32_t)))==NULL) {
             sd_err("failed to allocate memory for unique integers");
             return SD_ERR;
         }
         (*uints)[0] = ints[0];
         return SD_OK;
     }
     /* sort copy of input vector */
     if ((ints_copy = sd_malloc(sizeof(uint32_t) * n))==NULL) {
         sd_err("failed to allocate memory for ints copy.");
         return SD_ERR;
     }
     memcpy(ints_copy, ints, n*sizeof(uint32_t));
     qsort(ints_copy, n, sizeof(uint32_t), compare_int);
     /* count uniq */
     *nuniq = 1;
     for (i=0; i<(n-1); i++)
         if (ints_copy[i] != ints_copy[i+1])
             (*nuniq)++;
     if ((*uints = sd_malloc (sizeof(uint32_t) * *nuniq))==NULL) {
         sd_err("failed to allocate memory for unique integers.");
         sd_free(ints_copy);
         return SD_ERR;
     }
     /* copy unique into output array */
     j = 0;
     (*uints)[j++] = ints_copy[0];
     for (i=0; i<(n-1); i++)
         if (ints_copy[i] != ints_copy[i+1])
             (*uints)[j++] = ints_copy[i+1];
     sd_free(ints_copy);
     return SD_OK;
 }
uint32_t sd_ver_major ()
Definition at line 5 of file ver.c.
 { return 0; }
uint32_t sd_ver_minor ()
Definition at line 7 of file ver.c.
 { return 0; }
Variable Documentation
sd_log_msg_fp sd_log_msg
Definition at line 5 of file sd_log.c.
Referenced by sd_log_get_msg(), and sd_log_set_msg().