sddekit: sd_sch Struct Reference
sd_sch Struct Reference
#include <sddekit.h>
Data Fields
void * ptr
uint32_t(* get_nx)(sd_sch *)
sd_stat(* apply)(sd_sch *, sd_hist *, sd_rng *, sd_sys *, double t, double dt, uint32_t nx, double *restrict x, uint32_t nc, double *restrict c)
void(* free)(sd_sch *)
Detailed Description
Interface to time-stepping schemes.
Definition at line 1223 of file sddekit.h.
Field Documentation
sd_stat(* sd_sch::apply) (sd_sch *, sd_hist *, sd_rng *, sd_sys *, double t, double dt, uint32_t nx, double *restrict x, uint32_t nc, double *restrict c)
Apply scheme.
Parameters
data user data for scheme such as storage for intermediate steps.
hist history instance.
rng random number generator state.
sys system being solved.
sysd user data for system.
t current time.
dt current time step to use.
nx number of state variables.
x state variable vector.
nc number of coupling variables.
c coupling variable vector.
Returns
SD_OK if scheme succeeded, SD_ERR if error occurred.
Definition at line 1252 of file sddekit.h.
Referenced by sd_sch_new_emc(), and sd_sch_new_heun().
void(* sd_sch::free) (sd_sch *)
Free memory allocated for this scheme.
Definition at line 1260 of file sddekit.h.
Referenced by sd_sch_new_emc(), and sd_sch_new_heun().
uint32_t(* sd_sch::get_nx) (sd_sch *)
Get the number of state variables for which this scheme has memory allocated.
Parameters
d scheme instance.
Returns
number of state variables
Definition at line 1234 of file sddekit.h.
Referenced by sd_sch_new_emc(), and sd_sch_new_heun().
void* sd_sch::ptr
Definition at line 1225 of file sddekit.h.
Referenced by one_step_free(), sd_sch_new_cb(), sd_sch_new_emc(), and sd_sch_new_heun().
The documentation for this struct was generated from the following file:
src/sddekit.h