sddekit: src/sys_cb.c File Reference
sys_cb.c File Reference
#include "sddekit.h"
Data Structures
struct data
Typedefs
typedef struct data data
Functions
sd_sys * sd_sys_new_cb (uint32_t ndim, uint32_t ndc, uint32_t nobs, uint32_t nrpar, uint32_t nipar, void *user_data, sd_stat(*user_apply)(void *, sd_sys_in *, sd_sys_out *))
Typedef Documentation
typedef struct data data
Function Documentation
sd_sys* sd_sys_new_cb (uint32_t ndim, uint32_t ndc, uint32_t nobs, uint32_t nrpar, uint32_t nipar, void * user_data, sd_stat(*)(void *, sd_sys_in *, sd_sys_out *) user_apply)
Create new system based on user provided data & callback.
Definition at line 38 of file sys_cb.c.
References data::ndc, ndc(), data::ndim, ndim(), data::nipar, nipar(), data::nobs, nobs(), data::nrpar, nrpar(), sd_sys::ptr, sd_err, sd_malloc(), data::sys, data::user_apply, and data::user_data.
 {
     data *d;
         if ((d = sd_malloc(sizeof(data))) == NULL)
     {
         sd_err("alloc sys cb failed.");
         return NULL;
     }
     d->ndim = ndim;
     d->ndc = ndc;
     d->nobs = nobs;
     d->nrpar = nrpar;
     d->nipar = nipar;
     d->sys = defaults;
     d->sys.ptr = d;
     d->user_data = user_data;
     d->user_apply = user_apply;
     return &(d->sys);
 }