sddekit: src/sys_exc.c File Reference
sys_exc.c File Reference
#include "sddekit.h"
Data Structures
struct pars
struct data
Macros
#define GETSET(field)
Functions
uint32_t ndim (sd_sys *s)
uint32_t ndc (sd_sys *s)
uint32_t nobs (sd_sys *s)
uint32_t nrpar (sd_sys *s)
uint32_t nipar (sd_sys *s)
sd_sys * get_sys (sd_sys_exc *e)
sd_sys_exc * sd_sys_exc_new ()
Variables
struct pars pars_default = {.a=1.1, .tau=3.0, .D=1e-3, .k=0.01}
sd_sys sys_default
sd_sys_exc exc_default
Macro Definition Documentation
#define GETSET (field)
Value:
static double get_ ## field(sd_sys_exc *s) { \
    struct data *d = (struct data *) (*s->sys)(s)->ptr; \
    return d->pars.field; \
}\
static void set_ ## field(sd_sys_exc *s, double val) { \
    struct data *d = (struct data *) (*s->sys)(s)->ptr; \
    d->pars.field = val; \
}
Definition at line 20 of file sys_exc.c.
Function Documentation
sd_sys* get_sys (sd_sys_exc * e)
Definition at line 66 of file sys_exc.c.
References sd_sys_exc::ptr.
 { return &(((struct data *) e->ptr)->sys_if); }
uint32_t ndc (sd_sys * s)
Definition at line 50 of file sys_exc.c.
Referenced by sd_sys_new_cb().
 { (void) s;  return 1; }
uint32_t ndim (sd_sys * s)
Definition at line 49 of file sys_exc.c.
Referenced by sd_sys_new_cb().
 { (void) s;  return 2; }
uint32_t nipar (sd_sys * s)
Definition at line 53 of file sys_exc.c.
Referenced by sd_sys_new_cb().
 { (void) s;  return 0; }
uint32_t nobs (sd_sys * s)
Definition at line 51 of file sys_exc.c.
Referenced by sd_sys_new_cb().
 { (void) s;  return 1; }
uint32_t nrpar (sd_sys * s)
Definition at line 52 of file sys_exc.c.
Referenced by sd_sys_new_cb().
 { (void) s;  return 4; }
sd_sys_exc* sd_sys_exc_new ()
Create new instance of the Excitator system.
Definition at line 81 of file sys_exc.c.
References exc_default, data::exc_if, data::pars, pars_default, sd_sys::ptr, sd_sys_exc::ptr, sd_err, sd_malloc(), sys_default, and data::sys_if.
{
     struct data *d, zero = {0};
     if ((d = sd_malloc (sizeof(struct data))) == NULL)
     {
         sd_err("alloc exc sys failed.");
         return NULL;
     }
     *d = zero;
     d->pars = pars_default;
     d->sys_if = sys_default;
     d->exc_if = exc_default;
     d->sys_if.ptr = d->exc_if.ptr = d;
     return &(d->exc_if);
 }
Variable Documentation
sd_sys_exc exc_default
Initial value:
= {
    .ptr = NULL,
    .sys = &get_sys,
    .get_a = &get_a,
    .set_a = &set_a,
    .get_tau = &get_tau,
    .set_tau = &set_tau,
    .get_D = &get_D,
    .set_D = &set_D,
    .get_k = &get_k,
    .set_k = &set_k
}
Definition at line 68 of file sys_exc.c.
Referenced by sd_sys_exc_new().
struct pars pars_default = {.a=1.1, .tau=3.0, .D=1e-3, .k=0.01}
Definition at line 9 of file sys_exc.c.
Referenced by sd_sys_exc_new().
sd_sys sys_default
Initial value:
= {
    .ptr = NULL,
    .ndim = &ndim,
    .ndc = &ndc,
    .nobs = &nobs,
    .nrpar = &nrpar,
    .nipar = &nipar,
    .apply = &apply,
    .free = &exc_free
}
Definition at line 55 of file sys_exc.c.
Referenced by sd_sys_exc_new().