sddekit: src/sys_net.c File Reference
sys_net.c File Reference
#include "sddekit.h"
Data Structures
struct netd
Typedefs
typedef struct netd netd
Functions
uint32_t get_n (sd_net *net)
uint32_t get_m (sd_net *net)
uint32_t get_nnz (sd_net *net)
uint32_t * get_or (sd_net *net)
uint32_t get_or_i (sd_net *net, uint32_t i)
uint32_t * get_ic (sd_net *net)
uint32_t get_ic_i (sd_net *net, uint32_t i)
double * get_w (sd_net *net)
double get_w_i (sd_net *net, uint32_t i)
double * get_d (sd_net *net)
double get_d_i (sd_net *net, uint32_t i)
uint32_t get_ns (sd_net *net)
uint32_t get_ne (sd_net *net)
bool cn_is_null (sd_net *net)
uint32_t get_Ms_i (sd_net *net, uint32_t i)
uint32_t get_Ma_i (sd_net *net, uint32_t i)
uint32_t get_Me_i (sd_net *net, uint32_t i)
uint32_t get_M_i (sd_net *net, uint32_t i)
sd_sys * get_models_i (sd_net *net, uint32_t i)
bool get__init1 (sd_net *net)
sd_net * sd_net_new_hom (uint32_t n, sd_sys *sys, uint32_t ns, uint32_t na, uint32_t ne, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
sd_net * sd_net_new_het (uint32_t n, uint32_t m, uint32_t *restrict M, uint32_t *restrict Ms, uint32_t *restrict Ma, uint32_t *restrict Me, sd_sys **models, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
Typedef Documentation
typedef struct netd netd
Function Documentation
bool cn_is_null (sd_net * net)
Definition at line 31 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->cn == NULL; }
bool get__init1 (sd_net * net)
Definition at line 37 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->_init1; }
double* get_d (sd_net * net)
Definition at line 27 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->d; }
double get_d_i (sd_net * net, uint32_t i)
Definition at line 28 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->d[i]; }
uint32_t* get_ic (sd_net * net)
Definition at line 23 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->Ic; }
uint32_t get_ic_i (sd_net * net, uint32_t i)
Definition at line 24 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->Ic[i]; }
uint32_t get_m (sd_net * net)
Definition at line 19 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->m; }
uint32_t get_M_i (sd_net * net, uint32_t i)
Definition at line 35 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->M[i]; }
uint32_t get_Ma_i (sd_net * net, uint32_t i)
Definition at line 33 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->Ma[i]; }
uint32_t get_Me_i (sd_net * net, uint32_t i)
Definition at line 34 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->Me[i]; }
sd_sys* get_models_i (sd_net * net, uint32_t i)
Definition at line 36 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->models[i]; }
uint32_t get_Ms_i (sd_net * net, uint32_t i)
Definition at line 32 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->Ms[i]; }
uint32_t get_n (sd_net * net)
Definition at line 18 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->n; }
uint32_t get_ne (sd_net * net)
Definition at line 30 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->ne; }
uint32_t get_nnz (sd_net * net)
Definition at line 20 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->nnz; }
uint32_t get_ns (sd_net * net)
Definition at line 29 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->ns; }
uint32_t* get_or (sd_net * net)
Definition at line 21 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->Or; }
uint32_t get_or_i (sd_net * net, uint32_t i)
Definition at line 22 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->Or[i]; }
double* get_w (sd_net * net)
Definition at line 25 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->w; }
double get_w_i (sd_net * net, uint32_t i)
Definition at line 26 of file sys_net.c.
References sd_net::ptr.
 { return ((netd*)net->ptr)->w[i]; }
sd_net* sd_net_new_het (uint32_t n, uint32_t m, uint32_t *restrict M, uint32_t *restrict Ms, uint32_t *restrict Ma, uint32_t *restrict Me, sd_sys ** models, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
Create new instance of default network implementation.
Init network for general case of heterogeneous network of nm different models
Note
Further use requires filling data structures.
Parameters
d network to initialize.
n number of nodes in network.
m number of models used in network.
nnz number of non-zero elements in weights matrix.
w array of non-zero elements of weights matrix.
d array of delays per non-zero weight.
Returns
0 on success, 1 if error occurred.
Definition at line 181 of file sys_net.c.
References netd::_init1, netd::cn, netd::d, netd::Ic, netd::m, netd::M, M, netd::Ma, netd::Me, netd::models, netd::Ms, netd::n, netd::ne, netd::net_if, netd::nnz, netd::ns, netd::Or, sd_sys::ptr, sd_net::ptr, sd_err, sd_malloc(), netd::sys_if, and netd::w.
Referenced by sd_net_new_hom().
 {
     uint32_t i;
     netd *net = sd_malloc(sizeof(netd));
     if (net == NULL)
     {
         sd_err("net alloc failed.");
         return NULL;
     }
     net->net_if = net_defaults;
     net->sys_if = net_sys_defaults;
     net->net_if.ptr = net->sys_if.ptr = net;
     net->n = n;
     net->m = m;
     net->nnz = nnz;
     net->M = M;
     net->Ms = Ms;
     net->Ma = Ma;
     net->Me = Me;
     net->models = models;
     net->Or = Or;
     net->Ic = Ic; /* TODO ? same as Ie ? */
     net->w = w;
     net->d = d;
     /* intialize based on passed attributes: Ie, cne, cna */
     net->ns = 0;
     net->ne = 0;
     for (i=0; i<n; i++) {
         net->ns += net->Ms[net->M[i]];
         net->ne += net->Me[net->M[i]];
     }
     if ((net->cn = sd_malloc (sizeof(double) * net->ne))==NULL)
     {
         sd_err("failed to allocate memory for network.");
         return NULL;
     }
     net->_init1 = 0;
     return &(net->net_if);
 }
sd_net* sd_net_new_hom (uint32_t n, sd_sys * sys, uint32_t ns, uint32_t na, uint32_t ne, uint32_t nnz, uint32_t *restrict Or, uint32_t *restrict Ic, double *restrict w, double *restrict d)
Init network for homogeneous model case where m==1, simplifying setup.
Parameters
net network to initialize.
n number of nodes in network.
sys model system to use.
data user data for system.
ns number of state variables for system.
na number of afferent terms for system.
ne number of efferent terms for system.
nnz number of non-zero elements in weights matrix.
Or array of row offsets in non-zero arrays.
Ic array of column indices in non-zero arrays.
w array of non-zero elements of weights matrix.
d array of delays per non-zero weight.
Definition at line 72 of file sys_net.c.
References M, sd_net::ptr, sd_err, sd_free(), sd_malloc(), and sd_net_new_het().
 {
     uint32_t i, *M, *Ms, *Me, *Ma;
     sd_sys **models;
     char *errmsg;
     sd_net *net;
     M = Ms = Me = Ma = NULL;
     models = NULL;
     if ((M = sd_malloc (sizeof(uint32_t) * n))==NULL
      || (Ms = sd_malloc (sizeof(uint32_t)))==NULL
      || (Ma = sd_malloc (sizeof(uint32_t)))==NULL
      || (Me = sd_malloc (sizeof(uint32_t)))==NULL
      || (models = sd_malloc (sizeof(sd_sys*)))==NULL)
     {
         errmsg = "failed to allocate net init1 storage.";
         goto fail;
     }
     Ms[0] = ns;
     Ma[0] = na;
     Me[0] = ne;
     for(i=0; i<n; i++)
         M[i] = 0;
     models[0] = sys;
     if ((net = sd_net_new_het(n, 1, M, Ms, Ma, Me, models,
                     nnz, Or, Ic, w, d)) == NULL)
     {
         errmsg = "net initn failed.";
         goto fail;
     }
     ((netd*)net->ptr)->_init1 = true;
     return net;
 fail:
     if (M!=NULL) sd_free(M);
     if (Ms!=NULL) sd_free(Ms);
     if (Me!=NULL) sd_free(Me);
     if (Ma!=NULL) sd_free(Ma);
     if (models!=NULL) sd_free(models);
     sd_err(errmsg);
     return NULL;
 }